// A searchable, filterable reference of well-documented public cybersecurity
// history — malware, notable hackers, hacker groups, and major breaches.
// Same spirit as History mode (factual, terse, citation-free reference
// entries) but browsed by search + category filter instead of a timeline,
// since "when did this happen" matters far less here than "what kind of
// thing is this" and "find me the one called X."
export const CYBER_CATEGORIES = [
  { key: "malware", label: "Malware" },
  { key: "hacker", label: "Hackers" },
  { key: "group", label: "Hacker Groups" },
  { key: "breach", label: "Hacks & Breaches" },
];

export const CYBER_ENTRIES = [
  // ---- Malware ----
  {
    id: "morris-worm",
    category: "malware",
    name: "Morris Worm",
    year: "1988",
    summary: "One of the first internet worms, and the first to draw a federal conviction.",
    detail: "Written by Robert Tappan Morris as a self-propagating experiment to gauge the size of the internet, a bug in its spreading logic caused it to re-infect machines repeatedly, grinding an estimated 6,000 early internet computers to a halt. It led directly to the founding of the first CERT (Computer Emergency Response Team).",
    tags: ["worm", "internet", "cert"],
  },
  {
    id: "iloveyou",
    category: "malware",
    name: "ILOVEYOU",
    year: "2000",
    summary: "A self-mailing worm disguised as a love letter that infected tens of millions of Windows PCs in hours.",
    detail: "Spread as an email attachment named 'LOVE-LETTER-FOR-YOU.txt.vbs' — the double extension hid that it was an executable script. It overwrote files and emailed itself to every contact in the victim's address book, causing an estimated $10+ billion in damages worldwide.",
    tags: ["worm", "email", "social engineering", "philippines"],
  },
  {
    id: "code-red",
    category: "malware",
    name: "Code Red",
    year: "2001",
    summary: "A worm that defaced web servers and tried to launch a denial-of-service attack on the White House.",
    detail: "Exploited a buffer overflow in Microsoft's IIS web server software, infecting roughly 359,000 machines in under 14 hours by exploiting the flaw rather than requiring a user to open anything.",
    tags: ["worm", "buffer overflow", "iis", "ddos"],
  },
  {
    id: "slammer",
    category: "malware",
    name: "SQL Slammer",
    year: "2003",
    summary: "A worm so fast it doubled its infected population every 8.5 seconds.",
    detail: "At just 376 bytes, small enough to fit in a single network packet, Slammer infected most of its roughly 75,000 victims within ten minutes — one of the fastest-spreading pieces of malware ever recorded. It briefly knocked out South Korea's internet access almost entirely.",
    tags: ["worm", "sql server", "fast-spreading"],
  },
  {
    id: "stuxnet",
    category: "malware",
    name: "Stuxnet",
    year: "2010",
    summary: "The first malware widely believed to have been built to cause physical damage to industrial equipment.",
    detail: "Targeted the specific industrial control systems used at Iran's Natanz uranium enrichment facility, subtly speeding up and slowing down centrifuges to physically destroy them while feeding operators normal-looking readings. Its sophistication and specificity led researchers to attribute it to a nation-state effort.",
    tags: ["industrial control systems", "scada", "nation-state", "iran"],
  },
  {
    id: "cryptolocker",
    category: "malware",
    name: "CryptoLocker",
    year: "2013",
    summary: "One of the first ransomware strains to demand payment in Bitcoin, popularizing the modern ransomware model.",
    detail: "Encrypted victims' files and displayed a countdown timer demanding payment for the decryption key, spread mainly through email attachments and an existing botnet. Its takedown (Operation Tovar, 2014) recovered the private keys needed to decrypt files for free.",
    tags: ["ransomware", "encryption", "bitcoin", "botnet"],
  },
  {
    id: "wannacry",
    category: "malware",
    name: "WannaCry",
    year: "2017",
    summary: "A ransomware worm that hit over 200,000 computers across 150 countries in a single weekend.",
    detail: "Spread using EternalBlue, a Windows exploit believed to have been developed by the NSA and leaked publicly by a group called the Shadow Brokers. It crippled parts of the UK's National Health Service, forcing hospitals to turn away patients. A researcher accidentally halted its spread by registering an unregistered domain found in its code — a built-in 'kill switch.'",
    tags: ["ransomware", "worm", "eternalblue", "nhs", "kill switch"],
  },
  {
    id: "notpetya",
    category: "malware",
    name: "NotPetya",
    year: "2017",
    summary: "Disguised as ransomware, but built to destroy data with no way to pay for its return — the costliest cyberattack in history.",
    detail: "Spread via a compromised update to Ukrainian accounting software, then propagated using the same EternalBlue exploit as WannaCry. Despite showing a ransom note, its encryption was irreversible by design, causing an estimated $10 billion in damages to companies like Maersk and Merck. The US and UK governments attributed it to Russian military intelligence.",
    tags: ["wiper", "ransomware", "eternalblue", "ukraine", "nation-state"],
  },
  {
    id: "mirai",
    category: "malware",
    name: "Mirai",
    year: "2016",
    summary: "A botnet built from hacked security cameras and routers that launched history's largest DDoS attacks at the time.",
    detail: "Scanned the internet for IoT devices still using factory-default passwords, then enslaved them into a botnet used to flood targets with traffic. It took down large chunks of the internet, including Twitter, Netflix, and Reddit, in an October 2016 attack on DNS provider Dyn.",
    tags: ["botnet", "iot", "ddos", "default passwords"],
  },
  {
    id: "brain",
    category: "malware",
    name: "Brain",
    year: "1986",
    summary: "The first virus to infect IBM PC-compatible computers, written by two brothers in Pakistan.",
    detail: "Spread via floppy disk, Brain was relatively harmless — it displayed a message with the authors' names, address, and phone number, apparently as an advertisement for their computer shop, which was reportedly still fielding angry calls from victims years later.",
    tags: ["virus", "floppy disk", "pc"],
  },
  {
    id: "melissa",
    category: "malware",
    name: "Melissa",
    year: "1999",
    summary: "A fast-spreading macro virus disguised as an important document, emailed from a real, trusted contact.",
    detail: "Hidden inside a Word document, Melissa emailed itself to the first 50 contacts in each victim's address book — since it appeared to come from someone the recipient knew, far more people opened it than a typical stranger's email.",
    tags: ["macro virus", "email", "word document"],
  },
  {
    id: "zeus",
    category: "malware",
    name: "Zeus",
    year: "2007",
    summary: "A banking trojan that quietly stole login credentials by logging keystrokes in the victim's own browser.",
    detail: "Sold as a customizable crimeware kit on underground forums, Zeus (and its many variants) became one of the most widely used tools for online banking fraud, blamed for hundreds of millions of dollars in losses worldwide.",
    tags: ["trojan", "banking", "keylogger", "crimeware kit"],
  },
  {
    id: "conficker",
    category: "malware",
    name: "Conficker",
    year: "2008",
    summary: "A worm that infected an estimated 9-15 million Windows computers, forming one of the largest botnets ever recorded.",
    detail: "Its sheer scale and the sophistication of how it hid and updated itself alarmed security researchers enough to form the 'Conficker Working Group,' an unusual industry-wide coalition — yet its authors were never identified, and it was ultimately never used for anything more than sitting dormant.",
    tags: ["worm", "botnet"],
  },
  {
    id: "flame",
    category: "malware",
    name: "Flame",
    year: "2012",
    summary: "A highly sophisticated espionage tool that could record audio, screenshots, and keystrokes across Middle Eastern networks.",
    detail: "At roughly 20 megabytes, Flame was enormous for malware of its era, modular like a full software platform. Researchers found technical links suggesting the same team that built Stuxnet had a hand in it.",
    tags: ["espionage", "nation-state", "spyware", "middle east"],
  },
  {
    id: "petya",
    category: "malware",
    name: "Petya",
    year: "2016",
    summary: "Ransomware that encrypted an entire hard drive's file table at once, rather than files one at a time.",
    detail: "Instead of slowly encrypting individual files, Petya overwrote the master boot record and encrypted the disk's master file table, locking out the whole drive in one stroke — a precursor to the far more destructive NotPetya the following year, which reused some of its code.",
    tags: ["ransomware", "master boot record"],
  },
  {
    id: "emotet",
    category: "malware",
    name: "Emotet",
    year: "2014",
    summary: "Started as banking malware, then evolved into a rentable delivery platform for other gangs' ransomware.",
    detail: "Emotet's operators eventually stopped stealing money directly and instead sold infected-computer access to other criminal groups, functioning almost like a distribution service — international police coordinated a rare multi-country takedown of its infrastructure in 2021.",
    tags: ["trojan", "botnet", "malware-as-a-service"],
  },

  // ---- Hackers ----
  {
    id: "kevin-mitnick",
    category: "hacker",
    name: "Kevin Mitnick",
    year: "1980s–1995",
    summary: "Once the FBI's most-wanted hacker, later became a well-known security consultant and author.",
    detail: "Gained notoriety for breaking into the networks of companies like Nokia, Motorola, and Sun Microsystems, largely through social engineering rather than pure technical exploits. After serving five years in prison, he rebuilt his career as a security consultant and wrote several influential books on social engineering.",
    tags: ["social engineering", "phone phreaking"],
  },
  {
    id: "adrian-lamo",
    category: "hacker",
    name: "Adrian Lamo",
    year: "2001–2010",
    summary: "Known as 'the homeless hacker,' he broke into major networks from internet cafes, then reported the chat logs that led to Chelsea Manning's arrest.",
    detail: "Notable for breaking into The New York Times' internal network and Microsoft's systems, often disclosing the vulnerabilities to the companies himself. In 2010, he reported to authorities a chat in which Chelsea Manning described leaking classified documents to WikiLeaks — a decision that remains widely debated.",
    tags: ["disclosure", "wikileaks"],
  },
  {
    id: "gary-mckinnon",
    category: "hacker",
    name: "Gary McKinnon",
    year: "2001–2002",
    summary: "Carried out what US officials called 'the biggest military computer hack of all time' — looking for evidence of UFOs.",
    detail: "Broke into 97 US military and NASA computers, saying he was searching for suppressed evidence of extraterrestrial technology and free energy suppression. The US sought his extradition for years; the UK ultimately blocked it in 2012 on human-rights grounds related to his Asperger's diagnosis.",
    tags: ["nasa", "military", "extradition"],
  },
  {
    id: "george-hotz",
    category: "hacker",
    name: "George Hotz (geohot)",
    year: "2007–2011",
    summary: "First person to carrier-unlock an iPhone, then the first to publicly jailbreak the PlayStation 3.",
    detail: "Unlocked the original iPhone from AT&T exclusivity as a teenager in 2007, later reverse-engineering the PS3's security to allow running unauthorized software — which triggered a lawsuit from Sony that was settled out of court. He went on to found the self-driving car company comma.ai.",
    tags: ["jailbreak", "reverse engineering", "playstation", "iphone"],
  },
  {
    id: "aaron-swartz",
    category: "hacker",
    name: "Aaron Swartz",
    year: "2010–2013",
    summary: "A programmer and internet activist prosecuted for mass-downloading academic articles to make them freely available.",
    detail: "Co-creator of the RSS specification and a founder of Reddit, Swartz connected a laptop to MIT's network to bulk-download journal articles from JSTOR, intending to make publicly-funded research freely accessible. Facing decades in prison under an aggressive prosecution, he died by suicide in 2013 — his case became a rallying point for reforming US computer crime law.",
    tags: ["activism", "open access", "jstor"],
  },
  {
    id: "samy-kamkar",
    category: "hacker",
    name: "Samy Kamkar",
    year: "2005",
    summary: "Created the fastest-spreading virus of its time as a MySpace prank — it wasn't designed to spread at all.",
    detail: "His 'Samy' worm just added 'Samy is my hero' and an automatic friend request to anyone who viewed his profile — but each infected profile then infected everyone who viewed it, reaching over a million profiles in under 20 hours before MySpace was forced offline to contain it.",
    tags: ["worm", "myspace", "social network"],
  },
  {
    id: "barnaby-jack",
    category: "hacker",
    name: "Barnaby Jack",
    year: "2010",
    summary: "A security researcher famous for making an ATM spray out cash on stage, live at a security conference.",
    detail: "His 'ATM jackpotting' demonstration exposed serious flaws in cash machine software; he later turned his research toward the safety of medical devices like pacemakers and insulin pumps, showing they could potentially be remotely tampered with.",
    tags: ["atm", "security research", "medical devices"],
  },
  {
    id: "marcus-hutchins",
    category: "hacker",
    name: "Marcus Hutchins (MalwareTech)",
    year: "2017",
    summary: "Accidentally stopped the global spread of the WannaCry ransomware attack within hours of it breaking out.",
    detail: "While reverse-engineering a WannaCry sample, Hutchins registered a strange, unregistered domain name found in its code out of curiosity — that single act triggered a 'kill switch' built into the malware, halting its worldwide spread almost immediately.",
    tags: ["wannacry", "kill switch", "security research"],
  },

  // ---- Hacker Groups ----
  {
    id: "anonymous",
    category: "group",
    name: "Anonymous",
    year: "2003–present",
    summary: "A leaderless, decentralized collective known for coordinated protests, DDoS attacks, and data leaks under a shared identity.",
    detail: "Originating from the 4chan imageboard, Anonymous has no formal membership or hierarchy — anyone can act 'as Anonymous.' Notable campaigns have targeted the Church of Scientology (Project Chanology), ISIS-affiliated social media accounts, and various governments and corporations, often using the Guy Fawkes mask as a visual symbol.",
    tags: ["hacktivism", "decentralized", "ddos", "4chan"],
  },
  {
    id: "lulzsec",
    category: "group",
    name: "LulzSec",
    year: "2011",
    summary: "A short-lived but highly visible group that breached Sony, the CIA's website, and PBS in a 50-day spree, 'for the lulz.'",
    detail: "Splintered off from Anonymous, LulzSec's high-profile hacks and public taunting of victims via Twitter made global headlines before the group voluntarily disbanded after just 50 days. Several core members were later identified and prosecuted after a fellow member turned FBI informant.",
    tags: ["hacktivism", "sony", "cia", "informant"],
  },
  {
    id: "lazarus-group",
    category: "group",
    name: "Lazarus Group",
    year: "2009–present",
    summary: "A prolific hacking group linked by researchers to North Korea, blamed for the Sony Pictures hack and huge cryptocurrency thefts.",
    detail: "Believed to be state-sponsored, the group has been tied by security researchers and US authorities to the 2014 Sony Pictures hack (in apparent retaliation for the film 'The Interview'), the WannaCry ransomware, and billions of dollars in stolen cryptocurrency used to help fund North Korea's government.",
    tags: ["nation-state", "north korea", "sony pictures", "cryptocurrency"],
  },
  {
    id: "fancy-bear",
    category: "group",
    name: "Fancy Bear (APT28)",
    year: "2004–present",
    summary: "A Russian state-linked group best known for its role in the 2016 hack of the US Democratic National Committee.",
    detail: "Widely attributed by Western intelligence agencies to Russia's military intelligence agency (GRU), the group has targeted government, military, and political organizations across the world, most famously the DNC email hack and leak during the 2016 US presidential election.",
    tags: ["nation-state", "russia", "apt", "dnc"],
  },
  {
    id: "chaos-computer-club",
    category: "group",
    name: "Chaos Computer Club",
    year: "1981–present",
    summary: "Europe's largest hacker association, focused on security research, privacy advocacy, and public education.",
    detail: "Founded in Germany, the CCC has spent decades publicly demonstrating security flaws — including breaking biometric fingerprint scanners and voting-machine software — to push for better security practices and digital-rights policy, rather than for personal gain.",
    tags: ["europe", "advocacy", "security research"],
  },
  {
    id: "cult-of-the-dead-cow",
    category: "group",
    name: "Cult of the Dead Cow",
    year: "1984–present",
    summary: "One of the oldest hacking groups in existence, credited with coining the term 'hacktivism.'",
    detail: "Founded in a Lubbock, Texas, fast-food restaurant's meat locker (hence the name), cDc released Back Orifice in 1998 — a remote-administration tool built to embarrass Microsoft over Windows security holes, drawing wide attention to how vulnerable the OS really was. Members later included Beto O'Rourke, who went on to serve in Congress and run for US president.",
    tags: ["hacktivism", "back orifice", "windows security"],
  },
  {
    id: "l0pht",
    category: "group",
    name: "L0pht Heavy Industries",
    year: "1992–2000",
    summary: "A small hacker collective whose members testified to the US Senate that they could take down the entire internet in 30 minutes.",
    detail: "Operating out of a shared Boston loft space, L0pht built widely-used security tools (including the password-auditing tool L0phtCrack) and became an early, credible bridge between the hacker community and mainstream cybersecurity policy — several members went on to found respected security companies.",
    tags: ["security research", "congress", "l0phtcrack"],
  },
  {
    id: "legion-of-doom",
    category: "group",
    name: "Legion of Doom",
    year: "1984–1990s",
    summary: "An influential early hacking group whose rivalry with a competing group led to one of the first major hacking prosecutions.",
    detail: "Named after the villains in a Saturday-morning cartoon, LoD's feud with a rival group (Masters of Deception) escalated into tit-for-tat network attacks that drew federal attention, part of a wave of prosecutions across the hacking scene in the early 1990s.",
    tags: ["1980s", "phone phreaking", "rivalry"],
  },
  {
    id: "shadow-brokers",
    category: "group",
    name: "The Shadow Brokers",
    year: "2016–2017",
    summary: "An anonymous group that leaked a cache of powerful hacking tools believed to belong to the NSA.",
    detail: "Their leaks included EternalBlue, the Windows exploit that both WannaCry and NotPetya used to spread — turning what was reportedly a secret government cyberweapon into a tool any criminal group could freely use. The group's true identity was never publicly confirmed.",
    tags: ["nsa", "leak", "eternalblue", "nation-state"],
  },
  {
    id: "revil",
    category: "group",
    name: "REvil",
    year: "2019–2021",
    summary: "A ransomware-as-a-service gang responsible for some of the largest ransom demands in history.",
    detail: "REvil didn't just encrypt victims' files — it rented out its ransomware to other criminal 'affiliates' for a cut of the profits. It was blamed for a $70 million ransom demand after breaching a software vendor used by hundreds of other companies at once, until Russian authorities announced arrests of its members in 2022.",
    tags: ["ransomware-as-a-service", "extortion"],
  },
  {
    id: "cozy-bear",
    category: "group",
    name: "Cozy Bear (APT29)",
    year: "2008–present",
    summary: "A Russian state-linked espionage group blamed for the SolarWinds supply-chain attack and a parallel 2016 breach of the DNC.",
    detail: "Widely attributed to Russia's foreign intelligence service (SVR), Cozy Bear is known for slow, quiet, long-term espionage campaigns rather than loud, destructive attacks — the opposite operating style of its similarly-named but unrelated counterpart, Fancy Bear.",
    tags: ["nation-state", "russia", "apt", "solarwinds"],
  },
  {
    id: "syrian-electronic-army",
    category: "group",
    name: "Syrian Electronic Army",
    year: "2011–2018",
    summary: "A pro-government hacking group that hijacked major news outlets' social media accounts to spread propaganda and false news.",
    detail: "Best known for a 2013 hoax tweet from a hacked Associated Press account falsely claiming an explosion at the White House had injured the president — briefly wiping billions of dollars off the stock market before the tweet was revealed as fake.",
    tags: ["propaganda", "social media", "syria"],
  },

  // ---- Hacks & Breaches ----
  {
    id: "target-breach",
    category: "breach",
    name: "Target Data Breach",
    year: "2013",
    summary: "Attackers stole 40 million credit card numbers by first breaching a small HVAC contractor's network credentials.",
    detail: "Hackers gained an initial foothold using stolen login credentials from a third-party heating and air-conditioning vendor, then moved laterally into Target's payment systems to install malware on point-of-sale terminals during the holiday shopping season — a textbook example of third-party supply-chain risk.",
    tags: ["retail", "pos malware", "third-party risk"],
  },
  {
    id: "sony-pictures-hack",
    category: "breach",
    name: "Sony Pictures Hack",
    year: "2014",
    summary: "Attackers leaked unreleased films, employee salaries, and executive emails, and wiped much of Sony's internal network.",
    detail: "A group calling itself 'Guardians of Peace' breached Sony Pictures ahead of the release of 'The Interview,' a comedy about a plot to assassinate North Korea's leader. The FBI formally attributed the attack to North Korea, which the country denied.",
    tags: ["wiper", "leak", "north korea", "entertainment"],
  },
  {
    id: "opm-breach",
    category: "breach",
    name: "US Office of Personnel Management Breach",
    year: "2015",
    summary: "Background-check and fingerprint records for over 21 million current and former US federal employees were stolen.",
    detail: "One of the most damaging government breaches on record, exposing highly sensitive security-clearance background investigation files — including relationships, finances, and mental health history — for millions of federal employees and contractors, widely attributed to Chinese state-linked hackers.",
    tags: ["government", "nation-state", "personal data"],
  },
  {
    id: "equifax-breach",
    category: "breach",
    name: "Equifax Data Breach",
    year: "2017",
    summary: "The Social Security numbers of roughly 147 million Americans were exposed through an unpatched web framework vulnerability.",
    detail: "Attackers exploited a known, already-patched vulnerability in the Apache Struts web framework that Equifax had simply failed to update for months, exposing names, birth dates, addresses, and Social Security numbers for nearly half the US population.",
    tags: ["unpatched software", "personal data", "credit bureau"],
  },
  {
    id: "solarwinds-hack",
    category: "breach",
    name: "SolarWinds Supply Chain Attack",
    year: "2020",
    summary: "Attackers slipped malicious code into a routine software update, quietly compromising thousands of organizations at once.",
    detail: "Suspected Russian state-linked hackers compromised the build process for SolarWinds' Orion network-monitoring software, inserting a backdoor into an official signed update that was then automatically installed by roughly 18,000 customers, including multiple US federal agencies.",
    tags: ["supply chain", "nation-state", "backdoor", "russia"],
  },
  {
    id: "colonial-pipeline",
    category: "breach",
    name: "Colonial Pipeline Ransomware Attack",
    year: "2021",
    summary: "A ransomware attack on billing systems led the operator to shut down the largest fuel pipeline in the US as a precaution.",
    detail: "The DarkSide ransomware gang encrypted Colonial Pipeline's business (not operational) systems, but the company proactively halted the pipeline itself out of caution, causing fuel shortages and panic-buying across the US East Coast. Colonial paid roughly $4.4 million in ransom, part of which the FBI later recovered.",
    tags: ["ransomware", "critical infrastructure", "extortion"],
  },
  {
    id: "yahoo-breaches",
    category: "breach",
    name: "Yahoo Data Breaches",
    year: "2013–2014",
    summary: "The largest data breaches ever disclosed, ultimately affecting all 3 billion Yahoo accounts that existed.",
    detail: "Disclosed years after they happened, in the middle of Yahoo's acquisition by Verizon, the breaches knocked a reported $350 million off the sale price — a rare case of a cybersecurity incident directly and publicly affecting a corporate acquisition's price tag.",
    tags: ["personal data", "acquisition"],
  },
  {
    id: "ashley-madison-hack",
    category: "breach",
    name: "Ashley Madison Hack",
    year: "2015",
    summary: "Hackers leaked the private user data of a website marketed toward people seeking extramarital affairs.",
    detail: "A group calling itself 'The Impact Team' published names, addresses, and transaction data for millions of users, causing real-world fallout including reported divorces, resignations, and at least a few suicides linked to the exposure.",
    tags: ["leak", "personal data", "extortion"],
  },
  {
    id: "marriott-breach",
    category: "breach",
    name: "Marriott / Starwood Breach",
    year: "2018",
    summary: "Attackers sat undetected inside a hotel reservation system for four years, exposing up to 500 million guest records.",
    detail: "The intruders had actually breached Starwood's systems before Marriott acquired the chain, and the compromise simply carried over into Marriott's own network post-merger — going unnoticed for years and exposing passport numbers and travel history for hundreds of millions of guests.",
    tags: ["personal data", "hospitality", "long-term compromise"],
  },
  {
    id: "capital-one-breach",
    category: "breach",
    name: "Capital One Breach",
    year: "2019",
    summary: "A former cloud company employee exploited a misconfigured firewall to steal data on over 100 million customers.",
    detail: "The attacker exploited a specific cloud server misconfiguration (a server-side request forgery flaw) to trick a system into handing over credentials with far more access than intended — highlighting how a single cloud-configuration mistake can expose an enormous amount of data at once.",
    tags: ["cloud misconfiguration", "insider", "personal data"],
  },
  {
    id: "twitter-2020-hack",
    category: "breach",
    name: "2020 Twitter Bitcoin Hack",
    year: "2020",
    summary: "Attackers hijacked the verified accounts of Barack Obama, Elon Musk, Apple, and dozens of other high-profile accounts in one afternoon.",
    detail: "Rather than a technical exploit, the attackers used social engineering to trick Twitter employees into handing over access to internal admin tools, then posted a cryptocurrency scam from the hijacked accounts — a stark demonstration that even the biggest platforms can be undone by tricking a single employee.",
    tags: ["social engineering", "insider access", "cryptocurrency scam"],
  },
  {
    id: "moveit-breach",
    category: "breach",
    name: "MOVEit Mass Breach",
    year: "2023",
    summary: "A single flaw in widely-used file-transfer software let one ransomware gang steal data from thousands of organizations at once.",
    detail: "The Clop ransomware gang exploited a previously unknown vulnerability in the MOVEit file-transfer tool, hitting government agencies, universities, and corporations worldwide simultaneously — an example of how one flaw in shared, unglamorous infrastructure software can cascade into an enormous number of victims at once.",
    tags: ["supply chain", "ransomware", "file transfer"],
  },
];
