// Concept-of-the-day content. Each entry: {id, subject, title, blurb, whyItMatters,
// anim:{kind, params}, tryIt:{mode, label}}. params.caps (optional) overrides the
// kind's 3 default captions. Facts are kept conservative and hedged where needed.

const M = { physics: "Physics", chemistry: "Chemistry", astronomy: "Astronomy", history: "History", cybersecurity: "Cybersecurity", mathematics: "Mathematics", economics: "Economics", zoology: "Zoology", sound: "Sound", sustainability: "Sustainability", genetics: "Genetics", whiteboard: "Whiteboard" };
const S = { physics: "Physics", chemistry: "Chemistry", astronomy: "Astronomy", history: "History of Science", cybersecurity: "Cybersecurity", mathematics: "Mathematics", economics: "Economics", zoology: "Zoology", genetics: "Genetics", sound: "Sound", sustainability: "Sustainability" };

function c(id, subject, title, blurb, whyItMatters, kind, params, mode) {
  return { id, subject: S[subject], title, blurb, whyItMatters, anim: { kind, params }, tryIt: { mode, label: `Try it in ${M[mode]}` } };
}

export const CONCEPTS = [
  // ---- Physics ----
  c("sideways-and-down", "physics", "Sideways and Down Are Independent",
    "Gravity pulls only downward, so it changes a projectile's vertical speed but not its horizontal speed. Ignoring air, a ball shot flat and a ball dropped at the same moment hit the ground together.",
    "Every thrown ball and water arc follows this rule.", "projectile",
    { angle: 30, caps: ["1. Launch with a sideways and an upward speed.", "2. Sideways speed stays steady; vertical speed changes.", "3. Together they trace a parabola."] }, "physics"),
  c("forty-five-degrees", "physics", "The 45-Degree Launch",
    "On level ground with no air, a projectile goes farthest when launched at 45 degrees. Angles the same distance above and below 45, such as 30 and 60, land at the same spot.",
    "It is a handy rule for sports, sprinklers and cannons alike.", "projectile",
    { angle: 45, caps: ["1. Launch at 45 degrees.", "2. Height and distance are balanced.", "3. This angle gives the longest range."] }, "physics"),
  c("pendulum-period", "physics", "Pendulum Timing",
    "For small swings, a pendulum's period depends on its length and on gravity, not on the mass of the bob or how wide it swings. The formula is about T = 2π√(L/g).",
    "Pendulums powered accurate clocks for centuries.", "pendulum", { amp: 0.4, period: 3 }, "physics"),
  c("energy-swap", "physics", "Energy Swaps Back and Forth",
    "A swinging pendulum trades gravitational potential energy (height) for kinetic energy (speed) and back. Without friction the total stays the same, so it would swing forever.",
    "Energy conservation lets us predict motion without tracking every force.", "pendulum", { amp: 1.0 }, "physics"),
  c("hookes-law", "physics", "Hooke's Law",
    "A spring pulls back with a force proportional to how far it is stretched or squeezed: F = −kx. That steady pull-back produces smooth back-and-forth motion whose period depends on the mass and the spring's stiffness, not the size of the stretch.",
    "It underlies scales, car suspensions and even vibrating atoms.", "spring", { damp: 0 }, "physics"),
  c("damping", "physics", "Why Swings Slow Down",
    "Friction and air drag steal a little energy from an oscillator on every swing, turning it into heat. The amplitude shrinks smoothly until the motion stops. This is called damping.",
    "Shock absorbers and door closers use damping on purpose.", "spring",
    { damp: 0.28, caps: ["1. Start the mass oscillating.", "2. Each swing loses a little energy to friction.", "3. The motion fades away."] }, "physics"),
  c("resonance", "physics", "Resonance",
    "Every oscillator has a natural rhythm. Pushing at that rhythm, like timing pushes on a swing, adds energy with every cycle and the swings grow large. Pushing at the wrong rhythm mostly cancels out.",
    "Radios, musical instruments and MRI machines all rely on resonance.", "pendulum",
    { amp: 0.8, caps: ["1. A swing has a natural rhythm.", "2. Push in time with it and it gains energy.", "3. Small, well-timed pushes build big swings."] }, "sound"),
  c("superposition", "physics", "Waves Add Up",
    "When two waves overlap, the medium simply follows their sum. Where a peak meets a peak the wave grows (constructive interference); where a peak meets a trough they cancel (destructive). The waves then continue on unchanged.",
    "It explains rainbows on soap bubbles, radio dead spots and more.", "waves", { f1: 3, f2: 4 }, "physics"),
  c("incline-slide", "physics", "Sliding Down a Ramp",
    "On a slope, gravity splits into a part pressing into the ramp and a part along it, of size mg sinθ. The block slides only if that push beats friction. A steeper ramp or a slicker surface makes sliding more likely.",
    "Roads, ramps and loading docks are all designed around this balance.", "incline", { angle: 35, mu: 0.2 }, "physics"),
  c("static-friction", "physics", "Friction Holds On",
    "Static friction pushes back just as hard as needed, up to a maximum of μ times the normal force. On a gentle ramp with a grippy surface, it fully balances the pull of gravity along the slope and the block stays put.",
    "Without it, parked cars would roll away on any hill.", "incline", { angle: 20, mu: 0.6 }, "physics"),
  c("elastic-collision", "physics", "Bouncy Collisions",
    "In an elastic collision both momentum and kinetic energy are conserved. When equal masses collide head-on and one starts at rest, they swap velocities, which is why a Newton's cradle passes motion along the row.",
    "Elastic collisions model billiard balls and colliding gas molecules.", "collision", { elastic: true }, "physics"),
  c("inelastic-collision", "physics", "Sticky Collisions",
    "In an inelastic collision momentum is still conserved, but some kinetic energy turns into heat, sound or deformation. When two equal carts stick together, they move off at half the original speed and half the kinetic energy is gone.",
    "Car crumple zones use this: energy goes into bending metal instead of you.", "collision", { elastic: false }, "physics"),
  c("momentum-conserved", "physics", "Momentum Is Conserved",
    "If nothing pushes from outside, the total momentum (mass times velocity) of a system cannot change. When a heavy cart hits a light one, the light one takes off faster but the total stays the same.",
    "It lets us analyse crashes, rockets and explosions without knowing the forces.", "collision",
    { elastic: true, m1: 2, m2: 1, caps: ["1. A heavy cart approaches a light one.", "2. They collide; the total momentum stays the same.", "3. The light cart shoots ahead faster."] }, "physics"),
  // ---- Chemistry ----
  c("electron-shells", "chemistry", "Electron Shells",
    "Electrons sit in shells around the nucleus. The first shell holds up to 2 electrons and the second up to 8. Sodium has 11 electrons, arranged 2, 8, 1.",
    "The shell pattern explains the layout of the periodic table.", "atom", { shells: [2, 8, 1] }, "chemistry"),
  c("noble-gas-stable", "chemistry", "Why Neon Doesn't React",
    "Neon has 10 electrons: 2 in the first shell and 8 in the second, so its outer shell is full. A full outer shell is very stable, which is why noble gases rarely form compounds.",
    "Atoms react to get stable shells, the idea behind most chemistry.", "atom",
    { shells: [2, 8], caps: ["1. Neon's nucleus holds 10 protons.", "2. Its electrons fill two shells: 2 and 8.", "3. A full outer shell means it hardly reacts."] }, "chemistry"),
  c("carbon-four", "chemistry", "Carbon's Four Bonds",
    "Carbon has 6 electrons: 2 in the first shell and 4 in the outer one. With four spots to fill, it can form four bonds, so it builds chains, rings and the huge variety of molecules of life.",
    "It is why carbon is the backbone of organic chemistry.", "atom",
    { shells: [2, 4], caps: ["1. Carbon has 6 protons in its nucleus.", "2. Two electrons fill shell one; four are in shell two.", "3. Four open slots let it bond four ways."] }, "chemistry"),
  c("ionic-bond", "chemistry", "Ionic Bonds: Give and Take",
    "Sodium easily gives up its one outer electron and chlorine readily gains one. The result is Na⁺ and Cl⁻ ions, and opposite charges attract to build table salt.",
    "It explains why salts dissolve in water and conduct electricity when melted.", "molecule", { mode: "ionic" }, "chemistry"),
  c("covalent-bond", "chemistry", "Covalent Bonds: Sharing",
    "Two hydrogen atoms each have one electron. By sharing a pair, each atom acts as if its first shell were full, and the atoms are held together as an H₂ molecule.",
    "Most molecules you meet, from water to DNA, are covalent.", "molecule", { mode: "covalent" }, "chemistry"),
  c("mass-conserved", "chemistry", "Atoms Are Rearranged, Not Lost",
    "In a chemical reaction the atoms are the same before and after; only the bonds change. In 2H₂ + O₂ → 2H₂O, four hydrogens and two oxygens go in and come out.",
    "Balancing equations relies on this conservation of mass.", "molecule", { mode: "reaction" }, "chemistry"),
  c("half-life", "chemistry", "Half-Life",
    "A radioactive sample loses half of its unstable nuclei in each half-life, no matter how much is left. Carbon-14 has a half-life of about 5,730 years, which lets scientists date ancient organic remains.",
    "It powers radiocarbon dating and helps plan nuclear medicine and waste storage.", "exponential",
    { mode: "decay", unit: "half-life", caps: ["1. Start with a full sample.", "2. After one half-life, half remains.", "3. Halve again and again; it fades but never quite hits zero."] }, "chemistry"),
  c("temperature-is-motion", "chemistry", "Heat Is Jiggling Particles",
    "Temperature reflects the average kinetic energy of a substance's particles. Warm a solid enough and its particles jiggle free of their spots (melting); warm a liquid more and they fly apart (boiling).",
    "It links the tiny world of atoms to everyday hot and cold.", "phase", {}, "chemistry"),
  c("melting-plateau", "chemistry", "Melting Takes Energy, Not Temperature",
    "While ice melts at 0°C, added heat does not raise the temperature; it goes into breaking the bonds holding the crystal. The temperature climbs again only after all the ice has melted.",
    "It is why ice keeps a drink cold so effectively.", "phase",
    { solid: "ice", liquid: "water", gas: "steam", caps: ["1. Ice absorbs heat.", "2. At the melting point, energy loosens the bonds.", "3. Only then does the liquid warm up."] }, "chemistry"),
  // ---- Astronomy ----
  c("keplers-first", "astronomy", "Orbits Are Ellipses",
    "Kepler found that planets travel in ellipses with the Sun at one focus, not perfect circles. Most planets' orbits are nearly circular; this animation exaggerates the stretch so you can see it.",
    "It replaced two thousand years of circles-on-circles models.", "orbit", { e: 0.55 }, "astronomy"),
  c("keplers-second", "astronomy", "Equal Areas, Equal Times",
    "A line from the Sun to a planet sweeps out equal areas in equal times. To do that, the planet must move faster when it is close to the Sun and slower when it is far away.",
    "It follows from conservation of angular momentum.", "orbit", { e: 0.6 }, "astronomy"),
  c("keplers-third", "astronomy", "Farther Planets Take Longer",
    "A planet's orbital period squared is proportional to the cube of its average distance from the Sun. Mercury takes about 88 days per orbit; Neptune takes roughly 165 years.",
    "Astronomers use it to weigh stars and find distant planets.", "orbit",
    { e: 0.2, caps: ["1. Planets orbit the same Sun.", "2. Farther out, gravity is weaker and paths are longer.", "3. So distant planets take far longer to go around."] }, "astronomy"),
  c("orbit-is-falling", "astronomy", "An Orbit Is Endless Falling",
    "An orbiting object is falling toward Earth but moving sideways so fast that it keeps missing. Astronauts on the space station feel weightless because they are in free fall, not because gravity is gone there.",
    "It is how every satellite stays up without engines pushing.", "orbit", { e: 0.05 }, "astronomy"),
  c("seasons-tilt", "astronomy", "Seasons Come from Tilt",
    "Earth's axis is tilted about 23.5 degrees, so each hemisphere leans toward or away from the Sun through the year. Earth is actually closest to the Sun in early January, in the northern winter.",
    "Distance to the Sun does not cause the seasons; the tilt does.", "orbit",
    { e: 0.02, caps: ["1. Earth circles the Sun on a nearly round path.", "2. Its axis stays tilted the same way.", "3. So sunlight is stronger for each hemisphere in turn."] }, "astronomy"),
  c("moon-phases", "astronomy", "Why the Moon Has Phases",
    "The Moon is always half-lit by the Sun. As it orbits Earth about every 27 days, we see different amounts of the lit half, and the full cycle of phases takes roughly 29.5 days.",
    "The cycle inspired many of the world's calendars.", "orbit",
    { e: 0, caps: ["1. The Moon orbits Earth.", "2. The Sun always lights half of it.", "3. From Earth we see more or less of that half."] }, "astronomy"),
  c("light-travel", "astronomy", "Sunlight Is Old News",
    "Light travels about 300,000 km every second, yet it still takes roughly 8 minutes to cross from the Sun to Earth. Sunlight reaches Neptune after around 4 hours. The spacing in the animation is not to scale.",
    "Looking far into space is also looking back in time.", "timeline",
    { events: [{ label: "Sun" }, { label: "Earth", year: "8 min" }, { label: "Jupiter", year: "43 min" }, { label: "Neptune", year: "4 h" }], title: "Light travel time from the Sun", caps: ["1. Light leaves the Sun.", "2. It reaches Earth in about 8 minutes.", "3. Neptune sees it hours later."] }, "astronomy"),
  // ---- History of science ----
  c("eratosthenes", "history", "Eratosthenes Measures the Earth",
    "Around 240 BCE, Eratosthenes compared the noon Sun's angle at two Egyptian cities. The angle difference, about 7 degrees, was roughly 1/50 of a circle, so Earth's circumference was about 50 times the distance between them. His answer was in the right range; its exact accuracy is debated because the length of his unit is uncertain.",
    "It shows that shadows and geometry can measure a planet.", "timeline",
    { events: [{ label: "Shadow at Syene", year: "noon" }, { label: "Shadow at Alexandria", year: "7°" }, { label: "Earth size", year: "~240 BCE" }], caps: ["1. At noon the Sun is overhead at Syene.", "2. In Alexandria it casts a shadow at about 7 degrees.", "3. That angle reveals the Earth's size."] }, "history"),
  c("scientific-revolution", "history", "The Sky Gets Rearranged",
    "Copernicus proposed a Sun-centred model in 1543. Kepler described elliptical orbits in 1609, Galileo saw Jupiter's moons in 1610, and Newton explained the motions with gravity in 1687.",
    "Each step turned astronomy from description into prediction.", "timeline",
    { events: [{ label: "Copernicus", year: 1543 }, { label: "Kepler", year: 1609 }, { label: "Galileo", year: 1610 }, { label: "Newton", year: 1687 }] }, "history"),
  c("mendeleev", "history", "Mendeleev's Bold Gaps",
    "In 1869 Dmitri Mendeleev arranged elements by atomic mass and repeating properties, leaving gaps for undiscovered ones. Gallium (1875), scandium (1879) and germanium (1886) later fit his predictions closely.",
    "A good model doesn't just organise facts; it predicts new ones.", "timeline",
    { events: [{ label: "Table + gaps", year: 1869 }, { label: "Gallium", year: 1875 }, { label: "Scandium", year: 1879 }, { label: "Germanium", year: 1886 }] }, "chemistry"),
  c("germ-theory", "history", "Microbes Explain Disease",
    "In 1847 Ignaz Semmelweis showed that handwashing cut deaths in a Vienna maternity ward. John Snow traced a cholera outbreak to a water pump in 1854, and Pasteur and Koch built germ theory in the following decades.",
    "Handwashing and clean water remain some of the best health tools we have.", "timeline",
    { events: [{ label: "Handwashing", year: 1847 }, { label: "Cholera pump", year: 1854 }, { label: "Pasteur", year: "1860s" }, { label: "Koch", year: 1882 }] }, "history"),
  c("electromagnetism", "history", "Light Is an Electromagnetic Wave",
    "Faraday showed in 1831 that changing magnetic fields create electric currents. Maxwell's equations of the 1860s predicted electromagnetic waves travelling at the speed of light, and Hertz produced radio waves in 1887.",
    "It led to power grids, radio and every wireless device.", "timeline",
    { events: [{ label: "Faraday", year: 1831 }, { label: "Maxwell", year: "1865" }, { label: "Hertz", year: 1887 }] }, "history"),
  c("double-helix", "history", "The Double Helix",
    "In 1953 James Watson and Francis Crick proposed DNA's double-helix structure, using X-ray data from Rosalind Franklin and Maurice Wilkins' lab, including Franklin's Photo 51. The structure suggested how genetic information could be copied.",
    "It opened the era of molecular biology and modern genetics.", "timeline",
    { events: [{ label: "Mendel's peas", year: 1866 }, { label: "Photo 51", year: 1952 }, { label: "Double helix", year: 1953 }] }, "genetics"),
  // ---- Cybersecurity ----
  c("hash-avalanche", "cybersecurity", "Hashes: Digital Fingerprints",
    "A hash function turns any input into a short, fixed-size fingerprint. Change even one character and the fingerprint changes almost completely, the avalanche effect. Real hashes such as SHA-256 are longer than this toy demo.",
    "Hashes check that files are unchanged and protect stored passwords.", "hashing", { a: "cat", b: "cot" }, "cybersecurity"),
  c("file-integrity", "cybersecurity", "Checking a Download",
    "Websites often publish a hash of a file. After downloading, you compute the hash yourself; if even one bit differs, the hash will not match, warning you the file was corrupted or tampered with.",
    "It is a cheap way to spot a swapped or damaged file.", "hashing",
    { a: "app v1.0", b: "app v1.1", caps: ["1. Publisher shares a hash of the file.", "2. A single altered byte…", "3. …gives a totally different hash: mismatch!"] }, "cybersecurity"),
  c("salting", "cybersecurity", "Salting Passwords",
    "Sites should store a hash of your password, not the password itself. Adding a random 'salt' first means two users with the same password get different hashes and prebuilt lookup tables are useless.",
    "It limits the damage if a password database leaks.", "hashing",
    { a: "hunter2", b: "hunter2+x9Q", caps: ["1. A password is hashed.", "2. Add a random salt to it…", "3. …and the stored hash is completely different."] }, "cybersecurity"),
  c("caesar-cipher", "cybersecurity", "The Caesar Cipher",
    "Julius Caesar reportedly shifted each letter three places along the alphabet to hide messages. It is easy to crack today: there are only 25 possible shifts, and frequency analysis breaks it fast.",
    "It shows the basic idea of encryption and why strong keys matter.", "hashing", { mode: "caesar", shift: 3 }, "cybersecurity"),
  c("key-length", "cybersecurity", "Every Extra Bit Doubles the Work",
    "A cryptographic key with n bits has 2ⁿ possible values. Each added bit doubles the number of guesses an attacker needs, so modest increases in key length make brute-force attacks vastly harder.",
    "It is why modern keys are long, such as 128 or 256 bits.", "exponential",
    { unit: "bit added", caps: ["1. A 1-bit key has 2 possibilities.", "2. Each extra bit doubles the possibilities.", "3. The count explodes quickly."] }, "cybersecurity"),
  c("phishing-hash-check", "cybersecurity", "Tiny Changes, Big Differences",
    "Attackers rely on look-alike text such as 'paypa1' for 'paypal'. To a computer, one changed character is a completely different string, and hashing shows just how different.",
    "Checking URLs character by character can stop a phishing attempt.", "hashing",
    { a: "paypal", b: "paypa1", caps: ["1. Two web names look almost identical.", "2. One letter is swapped for a number.", "3. To a computer they are entirely different."] }, "cybersecurity"),
  // ---- Mathematics ----
  c("sieve", "mathematics", "The Sieve of Eratosthenes",
    "To find primes, list the numbers, then cross out multiples of 2, then of 3, then of 5, and so on. What survives has no smaller divisors, so it is prime. The full method continues up to the square root of the limit.",
    "It is one of the oldest algorithms and still teaches how to find primes.", "sorting", { mode: "primes" }, "mathematics"),
  c("number-line-negative", "mathematics", "Adding a Negative",
    "On a number line, adding moves right and adding a negative number moves left. Start at 0, move 3 right, then 5 left, and you end at −2, so 3 + (−5) = −2.",
    "The number line makes signed arithmetic feel like walking.", "sorting", { mode: "numberline", a: 3, b: -5 }, "mathematics"),
  c("bubble-sort", "mathematics", "Sorting by Swapping",
    "Bubble sort repeatedly compares neighbouring numbers and swaps them if they are out of order. Big values 'bubble' toward the end. It is simple but slow for large lists; faster algorithms exist.",
    "Sorting is everywhere in computing, from search results to spreadsheets.", "sorting", { mode: "sort" }, "mathematics"),
  c("doubling", "mathematics", "The Power of Doubling",
    "Doubling ten times multiplies a number by 1,024. Exponential growth starts slow and then becomes enormous, which is why our intuition often underestimates it.",
    "It underlies compound interest, viral spread and computer memory sizes.", "exponential", { unit: "step" }, "mathematics"),
  c("geometric-halving", "mathematics", "Halves That Add to One",
    "Add 1/2 + 1/4 + 1/8 + … and the total gets closer and closer to 1 without passing it. Infinite sums can have finite answers.",
    "It is the first taste of limits, the basis of calculus.", "exponential",
    { mode: "decay", unit: "step", caps: ["1. Take half of what is left.", "2. Then half of that, again and again.", "3. The pieces add up toward exactly 1."] }, "mathematics"),
  c("logarithms", "mathematics", "Logarithms Count the Doublings",
    "A logarithm asks 'how many times was it multiplied?' Since 2⁶ = 64, log base 2 of 64 is 6. Logarithms turn multiplication into addition and squash huge ranges into small numbers.",
    "Decibels, earthquake magnitudes and pH all use logarithmic scales.", "exponential",
    { unit: "step", caps: ["1. Each bar is double the last.", "2. The bar number counts the doublings.", "3. That count is the logarithm."] }, "mathematics"),
  c("signal-sum", "mathematics", "Adding Curves",
    "Add two sine waves point by point and you get a new wave. Complex signals, like a voice, can be built by adding many simple sine waves, an idea called Fourier analysis.",
    "It powers audio compression, image formats and radio.", "waves", { f1: 2, f2: 5 }, "mathematics"),
  // ---- Economics ----
  c("demand-up", "economics", "When Demand Rises",
    "If more people want a good, the demand curve shifts right. With supply unchanged, the market settles at a higher price and a higher quantity.",
    "It explains why hot days raise ice cream and umbrella prices.", "supplydemand", { shift: "demand", dir: 1 }, "economics"),
  c("demand-down", "economics", "When Demand Falls",
    "If tastes change or incomes fall, demand shifts left. With supply unchanged, both the equilibrium price and quantity drop.",
    "Businesses watch demand shifts to decide what to make.", "supplydemand", { shift: "demand", dir: -1 }, "economics"),
  c("supply-shock", "economics", "A Supply Shock",
    "A bad harvest or a broken supply chain shifts the supply curve left. With demand unchanged, the price rises and the quantity sold falls.",
    "It is why frost in a coffee region can raise coffee prices.", "supplydemand", { shift: "supply", dir: -1 }, "economics"),
  c("supply-up", "economics", "Better Technology Lowers Prices",
    "When production gets cheaper, the supply curve shifts right. With demand unchanged, the equilibrium price falls and more is sold.",
    "It is a big reason electronics keep getting cheaper for their power.", "supplydemand", { shift: "supply", dir: 1 }, "economics"),
  c("compound-interest", "economics", "Compound Interest",
    "Interest earned on interest makes money grow exponentially. The rule of 72 estimates the doubling time: divide 72 by the rate in percent, so 6% per year doubles money in about 12 years.",
    "Starting to save early matters more than saving a lot later.", "exponential",
    { unit: "12 years at 6%", caps: ["1. Money earns interest.", "2. Next time, interest is earned on the interest too.", "3. Growth speeds up, doubling roughly every 12 years at 6%."] }, "economics"),
  c("inflation-compounds", "economics", "Inflation Compounds Too",
    "Prices rising a few percent per year also compound. At 3% inflation, prices double in roughly 24 years (72 divided by 3), cutting what a fixed amount of money can buy.",
    "It's why savings need to earn more than inflation to keep their value.", "exponential",
    { unit: "24 years at 3%", caps: ["1. Prices rise a few percent each year.", "2. Each rise builds on the last.", "3. In about 24 years, prices at 3% double."] }, "economics"),
  // ---- Zoology / biology ----
  c("ten-percent", "zoology", "The 10% Rule",
    "Only about 10% of the energy at one feeding level (trophic level) is stored in the next level up; the rest is used for living or lost as heat. The exact figure varies by ecosystem.",
    "It explains why nature has far more plants than predators.", "foodchain", {}, "zoology"),
  c("rare-predators", "zoology", "Why Top Predators Are Rare",
    "Since energy shrinks at each step up the food chain, there is little left to support animals at the top. So predators like eagles or lions are far fewer than the grass eaters below them.",
    "Predators are most at risk when their habitat or prey shrinks.", "foodchain",
    { caps: ["1. Plants feed many plant-eaters.", "2. Those feed fewer predators.", "3. Very little energy reaches the top."] }, "zoology"),
  c("short-chains", "zoology", "Why Food Chains Are Short",
    "With about 90% of the energy lost at each link, most food chains have only 3 to 5 levels. There simply isn't enough energy left to support more.",
    "It shapes how ecosystems are structured worldwide.", "foodchain",
    { levels: [["Algae", "100,000"], ["Krill", "10,000"], ["Fish", "1,000"], ["Seal", "100"]], caps: ["1. Algae capture sunlight.", "2. Each meal passes on only a fraction.", "3. After a few steps, the energy runs out."] }, "zoology"),
  c("bacteria-doubling", "zoology", "Bacteria Doubling",
    "Under ideal conditions some bacteria, such as E. coli, can divide about every 20 minutes. Each division doubles the population, giving exponential growth until food or space run out.",
    "It explains why infections can escalate quickly and why food safety matters.", "exponential",
    { unit: "division", caps: ["1. One cell divides into two.", "2. Each of those divides again.", "3. Numbers explode until resources run out."] }, "zoology"),
  c("eat-lower", "zoology", "Eating Lower on the Food Chain",
    "Because energy shrinks at each level, growing plants for people to eat directly generally needs less land and energy than growing plants to feed animals that people then eat.",
    "It is one lens for thinking about sustainable food.", "foodchain",
    { levels: [["Crops", "10,000"], ["Livestock", "1,000"], ["People", "100"]], caps: ["1. Crops capture the sunlight.", "2. Feeding animals first loses most of the energy.", "3. Less remains for people at the top."] }, "sustainability"),
  // ---- Genetics ----
  c("punnett-3-1", "genetics", "The 3:1 Ratio",
    "If both parents carry one dominant (A) and one recessive (a) allele, each child has a 25% chance of AA, 50% of Aa and 25% of aa. Three in four will show the dominant trait, one in four the recessive trait.",
    "Mendel's pea experiments discovered this pattern in the 1860s.", "punnett", { p1: "Aa", p2: "Aa" }, "genetics"),
  c("test-cross", "genetics", "The Test Cross",
    "Crossing an Aa individual with an aa individual gives a 1:1 ratio of Aa to aa. Breeders use this to find out whether a dominant-looking plant or animal carries a hidden recessive allele.",
    "It reveals genotypes that appearances hide.", "punnett", { p1: "Aa", p2: "aa" }, "genetics"),
  c("uniform-f1", "genetics", "Pure Parents, Uniform Children",
    "Crossing a pure dominant parent (AA) with a pure recessive one (aa) makes every child Aa. All of them show the dominant trait, even though each carries a hidden recessive allele.",
    "It's how recessive traits can vanish for a generation and reappear later.", "punnett", { p1: "AA", p2: "aa" }, "genetics"),
  c("carriers", "genetics", "Carriers",
    "Some conditions, like cystic fibrosis, are recessive. Two carriers (Aa) each have a 25% chance with every child of having a child with the condition, and a 50% chance of a child who is a carrier.",
    "Genetic counselling uses these odds to help families plan.", "punnett",
    { p1: "Aa", p2: "Aa", caps: ["1. Both parents carry one recessive allele.", "2. Each pairing is equally likely.", "3. One in four children inherits two copies."] }, "genetics"),
  // ---- Sound ----
  c("pitch", "sound", "Pitch Is Frequency",
    "Sound is a vibration in the air. The number of vibrations per second is the frequency, measured in hertz. Higher frequency sounds higher; lower frequency sounds lower.",
    "It's the reason short piano strings play high notes.", "sound", { freq: 3 }, "sound"),
  c("loudness", "sound", "Loudness Is Amplitude",
    "The bigger the vibration, the more energy the wave carries and the louder we hear it. Every 10 decibels is a tenfold increase in sound intensity, which sounds roughly twice as loud.",
    "Knowing this helps protect your hearing.", "sound",
    { freq: 3, caps: ["1. A quiet sound has small vibrations.", "2. Louder sounds make the air vibrate more.", "3. Taller waves mean more energy."] }, "sound"),
  c("octave", "sound", "The Octave Doubles Frequency",
    "Two notes an octave apart have a frequency ratio of 2:1. The A above middle C is 440 hertz, and the A one octave higher is 880 hertz. We hear them as the same note, higher.",
    "It's the foundation of scales, tuning and harmony.", "sound",
    { freq: 3, caps: ["1. Play a note at some frequency.", "2. Double the frequency.", "3. You hear the same note an octave higher."] }, "sound"),
  c("beats", "sound", "Beats",
    "When two notes are close in pitch, their waves drift in and out of step. The sound swells and fades at a rate equal to the difference in their frequencies. Musicians listen for beats to tune instruments.",
    "It's a simple, sensitive way to tune a guitar.", "waves",
    { f1: 5, f2: 6, caps: ["1. Two nearly equal notes play together.", "2. Sometimes peaks align; sometimes they clash.", "3. The result rises and falls in loudness."] }, "sound"),
  c("noise-cancelling", "sound", "Noise-Cancelling Headphones",
    "Microphones on the headphones sample steady noise, and the electronics play an inverted copy. Peaks meet troughs and cancel, a case of destructive interference. It works best on steady, low-pitched sounds like engine hum.",
    "It makes flights and commutes quieter without turning up the music.", "waves",
    { f1: 3, f2: 3, phase2: Math.PI, caps: ["1. Noise arrives as a wave.", "2. The headphones make its mirror image.", "3. The two waves cancel out."] }, "sound"),
  c("speed-of-sound", "sound", "How Fast Is Sound?",
    "In air at about 20°C, sound travels around 343 metres per second, and faster in liquids and solids: roughly 1,480 m/s in water. It's why you see lightning before you hear thunder.",
    "Counting seconds between flash and bang estimates the storm's distance.", "timeline",
    { events: [{ label: "Lightning flash", year: "0 s" }, { label: "Thunder", year: "3 s ≈ 1 km" }], title: "Flash, then bang", caps: ["1. Lightning flashes; light arrives almost instantly.", "2. The sound wave travels about 343 metres every second.", "3. Seconds until thunder ÷ 3 gives kilometres."] }, "sound"),
  // ---- Sustainability ----
  c("greenhouse-natural", "sustainability", "The Natural Greenhouse Effect",
    "Gases like water vapour and carbon dioxide absorb heat radiated from the surface and send some of it back down. Without this natural effect Earth's average surface temperature would be around −18°C rather than about 15°C.",
    "It's the reason our planet is habitable.", "greenhouse", {}, "sustainability"),
  c("more-co2", "sustainability", "Adding More Greenhouse Gas",
    "Burning fossil fuels has raised carbon dioxide from about 280 parts per million before industrialisation to over 420 today. More greenhouse gas returns more heat, warming the planet.",
    "It's the core of human-driven climate change.", "greenhouse",
    { more: true }, "sustainability"),
  c("albedo", "sustainability", "Albedo: Reflected Sunlight",
    "Fresh snow reflects most incoming sunlight, while dark ocean water absorbs most of it. When ice melts it exposes darker surfaces, absorbing more heat and speeding up warming, a feedback loop.",
    "It's why polar regions are warming faster than the global average.", "greenhouse",
    { albedo: 0.8, caps: ["1. Bright ice reflects sunlight back to space.", "2. Dark surfaces absorb it instead.", "3. As ice melts, more heat is absorbed."] }, "sustainability"),
  c("solar-cost", "sustainability", "Falling Costs of Solar Power",
    "The cost of electricity from new solar farms fell by roughly 90% over the 2010s, according to major energy analyses. Manufacturing at scale and better technology keep pushing costs down.",
    "Cheaper clean power makes cutting emissions easier.", "exponential",
    { mode: "decay", unit: "big cost cut", caps: ["1. Solar panels start expensive.", "2. Each wave of scale and learning cuts the cost.", "3. Costs shrink steadily over time."] }, "sustainability"),
  c("heat-loss-chain", "sustainability", "Energy Is Never Lost, Only Spread Out",
    "Energy is conserved, but useful energy is not. Each conversion, like burning fuel or lighting a bulb, sends some out as low-grade heat. The numbers shown are illustrative; a real car engine turns roughly a quarter to a third of fuel energy into motion.",
    "Saving energy at the source avoids waste all the way down the chain.", "foodchain",
    { ratio: "", title: "Energy conversion chain (illustrative)", levels: [["Fuel", "100"], ["Engine", "35"], ["Drivetrain", "30"], ["Motion", "25"]], caps: ["1. Fuel starts with all its energy.", "2. Each step wastes some as heat.", "3. Only a fraction ends up doing the job."] }, "sustainability"),
];

// Keep the one-line facts-per-concept sensible for search/list UIs.
export function conceptById(id) { return CONCEPTS.find((c) => c.id === id) || null; }
