// The Dewey Decimal Classification's real second-summary table: the 10
// main classes (multiples of 100) and their 100 divisions (multiples of
// 10) exactly as published by OCLC/library systems worldwide — not a
// simplified or invented stand-in. Kept at the division level (not the
// full ~1,000 three-digit sections, and not the further decimal
// subdivisions) so every number and name here is one we can vouch for as
// the real, standard classification, rather than guessing at finer
// subject numbers from memory.
//
// `keywords` are search-only synonyms (genres/subjects a person might
// actually type) added on top of the real official caption, so "cooking"
// or "dinosaurs" still finds the right division even though the official
// caption says "Home & family management" or "Fossils & prehistoric life."
export const DEWEY_MAIN_CLASSES = [
  { code: "000", name: "Computer science, information & general works" },
  { code: "100", name: "Philosophy & psychology" },
  { code: "200", name: "Religion" },
  { code: "300", name: "Social sciences" },
  { code: "400", name: "Language" },
  { code: "500", name: "Science" },
  { code: "600", name: "Technology" },
  { code: "700", name: "Arts & recreation" },
  { code: "800", name: "Literature" },
  { code: "900", name: "History & geography" },
];

export const DEWEY_DIVISIONS = [
  { code: "000", name: "Computer science, knowledge & systems", keywords: ["computers", "software", "internet", "data"] },
  { code: "010", name: "Bibliographies", keywords: ["catalogs"] },
  { code: "020", name: "Library & information sciences", keywords: ["libraries", "archives"] },
  { code: "030", name: "Encyclopedias & books of facts", keywords: ["trivia", "reference"] },
  { code: "040", name: "[Unassigned]", keywords: [] },
  { code: "050", name: "Magazines, journals & serials", keywords: ["periodicals"] },
  { code: "060", name: "Associations, organizations & museums", keywords: ["clubs", "societies"] },
  { code: "070", name: "News media, journalism & publishing", keywords: ["newspapers", "reporting"] },
  { code: "080", name: "Quotations", keywords: ["quotes", "sayings"] },
  { code: "090", name: "Manuscripts & rare books", keywords: ["antiquarian"] },

  { code: "100", name: "Philosophy", keywords: ["reasoning", "existence"] },
  { code: "110", name: "Metaphysics", keywords: ["reality", "being"] },
  { code: "120", name: "Epistemology", keywords: ["knowledge", "causation"] },
  { code: "130", name: "Parapsychology & occultism", keywords: ["astrology", "psychics", "the paranormal", "tarot"] },
  { code: "140", name: "Philosophical schools of thought", keywords: [] },
  { code: "150", name: "Psychology", keywords: ["the mind", "behavior", "self-help"] },
  { code: "160", name: "Logic", keywords: ["argumentation"] },
  { code: "170", name: "Ethics", keywords: ["morality", "right and wrong"] },
  { code: "180", name: "Ancient, medieval & eastern philosophy", keywords: ["confucius", "buddhism as philosophy"] },
  { code: "190", name: "Modern western philosophy", keywords: [] },

  { code: "200", name: "Religion", keywords: ["theology", "spirituality", "faith"] },
  { code: "210", name: "Philosophy & theory of religion", keywords: ["god", "existence of god"] },
  { code: "220", name: "The Bible", keywords: ["scripture", "old testament", "new testament"] },
  { code: "230", name: "Christianity & Christian theology", keywords: [] },
  { code: "240", name: "Christian practice & observance", keywords: ["prayer", "devotionals"] },
  { code: "250", name: "Christian pastoral practice & religious orders", keywords: ["clergy", "monks", "nuns"] },
  { code: "260", name: "Christian organization, social work & worship", keywords: ["church", "sacraments"] },
  { code: "270", name: "History of Christianity", keywords: [] },
  { code: "280", name: "Christian denominations", keywords: ["catholicism", "protestantism", "orthodoxy"] },
  { code: "290", name: "Other religions", keywords: ["islam", "judaism", "hinduism", "buddhism", "mythology"] },

  { code: "300", name: "Social sciences, sociology & anthropology", keywords: ["society", "culture"] },
  { code: "310", name: "Statistics", keywords: ["data analysis", "surveys"] },
  { code: "320", name: "Political science", keywords: ["politics", "government", "elections"] },
  { code: "330", name: "Economics", keywords: ["money", "finance", "business cycles", "investing"] },
  { code: "340", name: "Law", keywords: ["legal", "constitutions", "crime and law"] },
  { code: "350", name: "Public administration & military science", keywords: ["the military", "armed forces", "war strategy"] },
  { code: "360", name: "Social problems & social services", keywords: ["criminology", "true crime", "welfare", "social work"] },
  { code: "370", name: "Education", keywords: ["schools", "teaching", "pedagogy"] },
  { code: "380", name: "Commerce, communications & transportation", keywords: ["trade", "shipping", "railroads"] },
  { code: "390", name: "Customs, etiquette & folklore", keywords: ["manners", "fairy tales", "legends", "traditions"] },

  { code: "400", name: "Language", keywords: ["linguistics", "grammar", "languages"] },
  { code: "410", name: "Linguistics", keywords: ["phonetics", "syntax"] },
  { code: "420", name: "English & Old English languages", keywords: [] },
  { code: "430", name: "German & related languages", keywords: ["dutch", "yiddish"] },
  { code: "440", name: "French & related languages", keywords: [] },
  { code: "450", name: "Italian, Romanian & related languages", keywords: [] },
  { code: "460", name: "Spanish & Portuguese languages", keywords: [] },
  { code: "470", name: "Latin & Italic languages", keywords: [] },
  { code: "480", name: "Classical & modern Greek languages", keywords: [] },
  { code: "490", name: "Other languages", keywords: ["arabic", "chinese", "japanese", "russian"] },

  { code: "500", name: "Science", keywords: ["natural science"] },
  { code: "510", name: "Mathematics", keywords: ["math", "algebra", "geometry", "calculus", "arithmetic"] },
  { code: "520", name: "Astronomy", keywords: ["space", "planets", "stars", "the solar system"] },
  { code: "530", name: "Physics", keywords: ["mechanics", "energy", "quantum physics"] },
  { code: "540", name: "Chemistry", keywords: ["chemicals", "reactions", "the periodic table"] },
  { code: "550", name: "Earth sciences & geology", keywords: ["rocks", "minerals", "volcanoes", "earthquakes", "weather", "climate"] },
  { code: "560", name: "Fossils & prehistoric life", keywords: ["dinosaurs", "paleontology"] },
  { code: "570", name: "Life sciences; biology", keywords: ["genetics", "evolution", "microbiology", "cells"] },
  { code: "580", name: "Plants (Botany)", keywords: ["gardening", "flowers", "trees"] },
  { code: "590", name: "Animals (Zoology)", keywords: ["pets", "wildlife", "insects", "dogs", "cats", "birds"] },

  { code: "600", name: "Technology", keywords: ["applied science", "engineering"] },
  { code: "610", name: "Medicine & health", keywords: ["nursing", "diseases", "anatomy", "nutrition"] },
  { code: "620", name: "Engineering", keywords: ["mechanical engineering", "electrical engineering", "civil engineering"] },
  { code: "630", name: "Agriculture", keywords: ["farming", "livestock", "crops"] },
  { code: "640", name: "Home & family management", keywords: ["cooking", "recipes", "food", "sewing", "housekeeping"] },
  { code: "650", name: "Management & public relations", keywords: ["business management", "advertising", "careers"] },
  { code: "660", name: "Chemical engineering", keywords: ["industrial chemistry"] },
  { code: "670", name: "Manufacturing", keywords: ["factories", "industrial processes"] },
  { code: "680", name: "Manufacture for specific uses", keywords: ["woodworking", "leatherwork"] },
  { code: "690", name: "Building & construction", keywords: ["carpentry", "architecture construction"] },

  { code: "700", name: "Arts", keywords: ["the arts"] },
  { code: "710", name: "Landscaping & area planning", keywords: ["urban planning", "parks"] },
  { code: "720", name: "Architecture", keywords: ["buildings design"] },
  { code: "730", name: "Sculpture, ceramics & metalwork", keywords: ["pottery"] },
  { code: "740", name: "Drawing & decorative arts", keywords: ["cartooning", "comics", "illustration"] },
  { code: "750", name: "Painting", keywords: ["paintings", "watercolor"] },
  { code: "760", name: "Graphic arts", keywords: ["printmaking"] },
  { code: "770", name: "Photography & computer art", keywords: ["photos", "digital art"] },
  { code: "780", name: "Music", keywords: ["songs", "instruments", "composers"] },
  { code: "790", name: "Sports, games & entertainment", keywords: ["sports", "games", "hobbies", "movies", "film", "tv"] },

  { code: "800", name: "Literature", keywords: ["books", "fiction", "poetry", "plays", "novels", "essays"] },
  { code: "810", name: "American literature in English", keywords: ["american fiction", "american poetry"] },
  { code: "820", name: "English & Old English literatures", keywords: ["british literature", "shakespeare"] },
  { code: "830", name: "German & related literatures", keywords: [] },
  { code: "840", name: "French & related literatures", keywords: [] },
  { code: "850", name: "Italian, Romanian & related literatures", keywords: [] },
  { code: "860", name: "Spanish & Portuguese literatures", keywords: [] },
  { code: "870", name: "Latin & Italic literatures", keywords: ["classical literature"] },
  { code: "880", name: "Classical & modern Greek literatures", keywords: ["greek myths as literature"] },
  { code: "890", name: "Other literatures", keywords: [] },

  { code: "900", name: "History & geography", keywords: ["history", "geography"] },
  { code: "910", name: "Geography & travel", keywords: ["maps", "atlases", "travel guides"] },
  { code: "920", name: "Biography & genealogy", keywords: ["biographies", "memoirs", "family history"] },
  { code: "930", name: "History of ancient world (to ca. 499)", keywords: ["ancient rome", "ancient greece", "ancient egypt"] },
  { code: "940", name: "History of Europe", keywords: ["world war", "european history"] },
  { code: "950", name: "History of Asia", keywords: ["chinese history", "japanese history"] },
  { code: "960", name: "History of Africa", keywords: ["african history"] },
  { code: "970", name: "History of North America", keywords: ["american history", "u.s. history", "canadian history"] },
  { code: "980", name: "History of South America", keywords: ["latin american history"] },
  { code: "990", name: "History of other areas", keywords: ["australian history", "pacific islands", "antarctica"] },
];

// The Dewey Decimal Classification's real THIRD-summary table: all 1,000
// three-digit sections (e.g. 512 Algebra, 641 Food & drink), one level
// finer than DEWEY_DIVISIONS above. Sourced from the DDC's own published
// third-summary list (the same standard table every library uses), not
// reconstructed from memory — a table this size is too easy to get subtly
// wrong by guessing, and the whole point of this feature is that every
// number and name here is real. "Not assigned or no longer used" and
// "[Unassigned]" entries are real too: the DDC genuinely leaves gaps
// (retired numbers, room for future expansion), it isn't a hole in this
// data.
export const DEWEY_SECTIONS = [
  { code: "000", name: "Computer science, information and general works" },
  { code: "001", name: "Knowledge" },
  { code: "002", name: "The book (writing, libraries, and book-related topics)" },
  { code: "003", name: "Systems" },
  { code: "004", name: "Data processing and computer science" },
  { code: "005", name: "Computer programming, programs, and data", keywords: ["coding", "software", "programming"] },
  { code: "006", name: "Special computer methods (e.g. AI, multimedia, VR)", keywords: ["ai", "artificial intelligence", "machine learning", "virtual reality"] },
  { code: "007", name: "[Unassigned]" },
  { code: "008", name: "[Unassigned]" },
  { code: "009", name: "[Unassigned]" },
  { code: "010", name: "Bibliography" },
  { code: "011", name: "Bibliographies" },
  { code: "012", name: "Bibliographies of individuals" },
  { code: "013", name: "[Unassigned]" },
  { code: "014", name: "Bibliographies of anonymous and pseudonymous works" },
  { code: "015", name: "Bibliographies of works from specific places" },
  { code: "016", name: "Bibliographies of works on specific subjects" },
  { code: "017", name: "General subject catalogs" },
  { code: "018", name: "Catalogs arranged by author, date, etc. [moved to 017]" },
  { code: "019", name: "Dictionary catalogs [moved to 017]" },
  { code: "020", name: "Library and information sciences" },
  { code: "021", name: "Library relationships (with archives, information centers, etc.)" },
  { code: "022", name: "Administration of physical plant" },
  { code: "023", name: "Personnel management" },
  { code: "024", name: "[Unassigned]" },
  { code: "025", name: "Library operations" },
  { code: "026", name: "Libraries for specific subjects" },
  { code: "027", name: "General libraries" },
  { code: "028", name: "Reading and use of other information media" },
  { code: "029", name: "[Unassigned]" },
  { code: "030", name: "General encyclopedic works" },
  { code: "031", name: "Encyclopedias in American English" },
  { code: "032", name: "Encyclopedias in English" },
  { code: "033", name: "Encyclopedias in other Germanic languages" },
  { code: "034", name: "Encyclopedias in French, Occitan, and Catalan" },
  { code: "035", name: "Encyclopedias in Italian, Romanian, and related languages" },
  { code: "036", name: "Encyclopedias in Spanish and Portuguese" },
  { code: "037", name: "Encyclopedias in Slavic languages" },
  { code: "038", name: "Encyclopedias in Scandinavian languages" },
  { code: "039", name: "Encyclopedias in other languages" },
  { code: "040", name: "Unassigned — formerly Biographies" },
  { code: "041", name: "[Unassigned]" },
  { code: "042", name: "[Unassigned]" },
  { code: "043", name: "[Unassigned]" },
  { code: "044", name: "[Unassigned]" },
  { code: "045", name: "[Unassigned]" },
  { code: "046", name: "[Unassigned]" },
  { code: "047", name: "[Unassigned]" },
  { code: "048", name: "[Unassigned]" },
  { code: "049", name: "[Unassigned]" },
  { code: "050", name: "General serial publications" },
  { code: "051", name: "Serials in American English" },
  { code: "052", name: "Serials in English" },
  { code: "053", name: "Serials in other Germanic languages" },
  { code: "054", name: "Serials in French, Occitan, and Catalan" },
  { code: "055", name: "Serials in Italian, Romanian, and related languages" },
  { code: "056", name: "Serials in Spanish and Portuguese" },
  { code: "057", name: "Serials in Slavic languages" },
  { code: "058", name: "Serials in Scandinavian languages" },
  { code: "059", name: "Serials in other languages" },
  { code: "060", name: "General organizations and museum science" },
  { code: "061", name: "Organizations in North America" },
  { code: "062", name: "Organizations in British Isles; in England" },
  { code: "063", name: "Organizations in central Europe; in Germany" },
  { code: "064", name: "Organizations in France and Monaco" },
  { code: "065", name: "Organizations in Italy and adjacent islands" },
  { code: "066", name: "Organizations in Iberian Peninsula and adjacent islands" },
  { code: "067", name: "Organizations in eastern Europe; in Russia" },
  { code: "068", name: "Organizations in other geographic areas" },
  { code: "069", name: "Museum science" },
  { code: "070", name: "News media, journalism, and publishing" },
  { code: "071", name: "Newspapers in North America" },
  { code: "072", name: "Newspapers in British Isles; in England" },
  { code: "073", name: "Newspapers in central Europe; in Germany" },
  { code: "074", name: "Newspapers in France and Monaco" },
  { code: "075", name: "Newspapers in Italy and adjacent islands" },
  { code: "076", name: "Newspapers in Iberian peninsula and adjacent islands" },
  { code: "077", name: "Newspapers in eastern Europe; in Russia" },
  { code: "078", name: "Newspapers in Scandinavia" },
  { code: "079", name: "Newspapers in other geographic areas" },
  { code: "080", name: "General collections" },
  { code: "081", name: "Collections in American English" },
  { code: "082", name: "Collections in English" },
  { code: "083", name: "Collections in other Germanic languages" },
  { code: "084", name: "Collections in French, Occitan, Catalan" },
  { code: "085", name: "Collections in Italian, Romanian, and related languages" },
  { code: "086", name: "Collections in Spanish and Portuguese" },
  { code: "087", name: "Collections in Slavic languages" },
  { code: "088", name: "Collections in Scandinavian languages" },
  { code: "089", name: "Collections in other languages" },
  { code: "090", name: "Manuscripts and rare books" },
  { code: "091", name: "Manuscripts" },
  { code: "092", name: "Block books" },
  { code: "093", name: "Incunabula" },
  { code: "094", name: "Printed books" },
  { code: "095", name: "Books notable for bindings" },
  { code: "096", name: "Books notable for illustrations" },
  { code: "097", name: "Books notable for ownership or origin" },
  { code: "098", name: "Prohibited works, forgeries, and hoaxes" },
  { code: "099", name: "Books notable for format" },
  { code: "100", name: "Philosophy and psychology" },
  { code: "101", name: "Theory of philosophy" },
  { code: "102", name: "Miscellany" },
  { code: "103", name: "Dictionaries and encyclopedias" },
  { code: "104", name: "No longer used — formerly Essays" },
  { code: "105", name: "Serial publications" },
  { code: "106", name: "Organizations and management" },
  { code: "107", name: "Education, research, related topics of philosophy" },
  { code: "108", name: "Groups of people" },
  { code: "109", name: "History and collected biography" },
  { code: "110", name: "Metaphysics" },
  { code: "111", name: "Ontology" },
  { code: "112", name: "No longer used — formerly Methodology" },
  { code: "113", name: "Cosmology (Philosophy of nature)" },
  { code: "114", name: "Space" },
  { code: "115", name: "Time" },
  { code: "116", name: "Change" },
  { code: "117", name: "Structure" },
  { code: "118", name: "Force and energy" },
  { code: "119", name: "Number and quantity" },
  { code: "120", name: "Epistemology, causation, and humankind" },
  { code: "121", name: "Epistemology (theory of knowledge)" },
  { code: "122", name: "Causation" },
  { code: "123", name: "Determinism and indeterminism" },
  { code: "124", name: "Teleology" },
  { code: "125", name: "No longer used — formerly Infinity" },
  { code: "126", name: "The self" },
  { code: "127", name: "The unconscious and the subconscious" },
  { code: "128", name: "Humankind" },
  { code: "129", name: "Origin and destiny of individual souls" },
  { code: "130", name: "Parapsychology and occultism" },
  { code: "131", name: "Parapsychological and occult methods for achieving well-being, happiness, success" },
  { code: "132", name: "No longer used — formerly Mental derangements" },
  { code: "133", name: "Specific topics in parapsychology and occultism", keywords: ["astrology", "tarot", "horoscope", "psychics"] },
  { code: "134", name: "No longer used — formerly Mesmerism and clairvoyance" },
  { code: "135", name: "Dreams and mysteries" },
  { code: "136", name: "No longer used — formerly Mental characteristics" },
  { code: "137", name: "Divinatory graphology" },
  { code: "138", name: "Physiognomy" },
  { code: "139", name: "Phrenology" },
  { code: "140", name: "Specific philosophical schools and viewpoints" },
  { code: "141", name: "Idealism and related systems and doctrines" },
  { code: "142", name: "Critical philosophy" },
  { code: "143", name: "Bergsonism and intuitionism" },
  { code: "144", name: "Humanism and related systems and doctrines" },
  { code: "145", name: "Sensationalism" },
  { code: "146", name: "Naturalism and related systems and doctrines" },
  { code: "147", name: "Pantheism and related systems and doctrines" },
  { code: "148", name: "Dogmatism, eclecticism, liberalism, syncretism, and traditionalism" },
  { code: "149", name: "Other philosophical systems and doctrines" },
  { code: "150", name: "Psychology" },
  { code: "151", name: "No longer used — formerly Intellect" },
  { code: "152", name: "Sensory perception, movement, emotions, and physiological drives" },
  { code: "153", name: "Conscious mental processes and intelligence" },
  { code: "154", name: "Subconscious and altered states and processes" },
  { code: "155", name: "Differential and developmental psychology" },
  { code: "156", name: "Comparative psychology" },
  { code: "157", name: "No longer used — formerly Emotions" },
  { code: "158", name: "Applied psychology", keywords: ["self-help", "self improvement"] },
  { code: "159", name: "No longer used — formerly Will" },
  { code: "160", name: "Philosophical logic" },
  { code: "161", name: "Induction" },
  { code: "162", name: "Deduction" },
  { code: "163", name: "Not assigned or no longer used" },
  { code: "164", name: "Not assigned or no longer used" },
  { code: "165", name: "Fallacies and sources of error" },
  { code: "166", name: "Syllogisms" },
  { code: "167", name: "Hypotheses" },
  { code: "168", name: "Argument and persuasion" },
  { code: "169", name: "Analogy" },
  { code: "170", name: "Ethics (moral philosophy)" },
  { code: "171", name: "Ethical systems" },
  { code: "172", name: "Political ethics" },
  { code: "173", name: "Ethics of family relationships" },
  { code: "174", name: "Occupational ethics" },
  { code: "175", name: "Ethics of recreation, leisure, public performances, communication" },
  { code: "176", name: "Ethics of sex and reproduction" },
  { code: "177", name: "Ethics of social relations" },
  { code: "178", name: "Ethics of consumption" },
  { code: "179", name: "Other ethical norms" },
  { code: "180", name: "Ancient, medieval, Eastern philosophy" },
  { code: "181", name: "Eastern philosophy" },
  { code: "182", name: "Pre-Socratic Greek philosophies" },
  { code: "183", name: "Sophistic, Socratic, related Greek philosophies" },
  { code: "184", name: "Platonic philosophy" },
  { code: "185", name: "Aristotelian philosophy" },
  { code: "186", name: "Skeptic and Neoplatonic philosophies" },
  { code: "187", name: "Epicurean philosophy" },
  { code: "188", name: "Stoic philosophy" },
  { code: "189", name: "Medieval Western philosophy" },
  { code: "190", name: "Modern Western and other non-eastern philosophy" },
  { code: "191", name: "Philosophy of the United States and Canada" },
  { code: "192", name: "Philosophy of the British Isles" },
  { code: "193", name: "Philosophy of Germany and Austria" },
  { code: "194", name: "Philosophy of France" },
  { code: "195", name: "Philosophy of Italy" },
  { code: "196", name: "Philosophy of Spain and Portugal" },
  { code: "197", name: "Philosophy of Russia" },
  { code: "198", name: "Philosophy of Scandinavia and Finland" },
  { code: "199", name: "Philosophy in other geographic areas" },
  { code: "200", name: "Religion" },
  { code: "201", name: "Religious mythology, general classes of religion, interreligious relations and attitudes, social theology" },
  { code: "202", name: "Doctrines" },
  { code: "203", name: "Public worship and other practices" },
  { code: "204", name: "Religious experience, life, practice" },
  { code: "205", name: "Religious ethics" },
  { code: "206", name: "Leaders and organization" },
  { code: "207", name: "Missions and religious education" },
  { code: "208", name: "Sources" },
  { code: "209", name: "Sects and reform movements" },
  { code: "210", name: "Philosophy and theory of religion" },
  { code: "211", name: "Concepts of God" },
  { code: "212", name: "Existence, ways of knowing God, attributes of God" },
  { code: "213", name: "Creation" },
  { code: "214", name: "Theodicy" },
  { code: "215", name: "Science and religion" },
  { code: "216", name: "No longer used—formerly Evil" },
  { code: "217", name: "No longer used—formerly Prayer" },
  { code: "218", name: "Humankind" },
  { code: "219", name: "No longer used—formerly Analogies" },
  { code: "220", name: "Bible" },
  { code: "221", name: "Old Testament (Tanakh)" },
  { code: "222", name: "Historical books of Old Testament" },
  { code: "223", name: "Poetic books of Old Testament" },
  { code: "224", name: "Prophetic books of Old Testament" },
  { code: "225", name: "New Testament" },
  { code: "226", name: "Gospels and Acts" },
  { code: "227", name: "Epistles" },
  { code: "228", name: "Revelation (Apocalypse)" },
  { code: "229", name: "Apocrypha, pseudepigrapha, and inter-testamental works" },
  { code: "230", name: "Christianity" },
  { code: "231", name: "God" },
  { code: "232", name: "Jesus Christ and his family" },
  { code: "233", name: "Humankind" },
  { code: "234", name: "Salvation and grace" },
  { code: "235", name: "Spiritual beings" },
  { code: "236", name: "Eschatology" },
  { code: "237", name: "No longer used—formerly Future state" },
  { code: "238", name: "Creeds, confessions of faith, covenants, and catechisms" },
  { code: "239", name: "Apologetics and polemics" },
  { code: "240", name: "Christian moral and devotional theology" },
  { code: "241", name: "Christian ethics" },
  { code: "242", name: "Devotional literature" },
  { code: "243", name: "Evangelistic writings for individuals and families" },
  { code: "244", name: "No longer used—formerly Religious fiction" },
  { code: "245", name: "No longer used—formerly Hymnology" },
  { code: "246", name: "Use of art in Christianity" },
  { code: "247", name: "Church furnishings and related articles" },
  { code: "248", name: "Christian experience, practice, life" },
  { code: "249", name: "Christian observances in family life" },
  { code: "250", name: "Local Christian church and Christian religious orders" },
  { code: "251", name: "Preaching (Homiletics)" },
  { code: "252", name: "Texts of sermons" },
  { code: "253", name: "Pastoral office and work (Pastoral theology)" },
  { code: "254", name: "Parish administration" },
  { code: "255", name: "Religious congregations and orders" },
  { code: "256", name: "No longer used — formerly Religious societies" },
  { code: "257", name: "No longer used — formerly Parochial schools, libraries, etc." },
  { code: "258", name: "No longer used — formerly Parochial medicine" },
  { code: "259", name: "Pastoral care of families, of specific groups of people" },
  { code: "260", name: "Christian social and ecclesiastical theology" },
  { code: "261", name: "Social theology and interreligious relations and attitudes" },
  { code: "262", name: "Ecclesiology" },
  { code: "263", name: "Days, times, places of religious observance" },
  { code: "264", name: "Public worship" },
  { code: "265", name: "Sacraments, other rites and acts" },
  { code: "266", name: "Missions" },
  { code: "267", name: "Associations for religious work" },
  { code: "268", name: "Religious education" },
  { code: "269", name: "Spiritual renewal" },
  { code: "270", name: "History, geographic treatment, biography of Christianity" },
  { code: "271", name: "Religious congregations and orders in church history" },
  { code: "272", name: "Persecutions in church history" },
  { code: "273", name: "Doctrinal controversies and heresies in general church history" },
  { code: "274", name: "Christianity in Europe" },
  { code: "275", name: "Christianity in Asia" },
  { code: "276", name: "Christianity in Africa" },
  { code: "277", name: "Christianity in North America" },
  { code: "278", name: "Christianity in South America" },
  { code: "279", name: "History of Christianity in other areas" },
  { code: "280", name: "Denominations and sects of Christian church" },
  { code: "281", name: "Early church and Eastern churches" },
  { code: "282", name: "Roman Catholic Church" },
  { code: "283", name: "Anglican churches" },
  { code: "284", name: "Protestant denominations of continental origin (Lutheran, Continental Reformed)" },
  { code: "285", name: "Presbyterian churches, Reformed churches centered in America, Congregational churches" },
  { code: "286", name: "Baptist, Restoration Movement, Adventist churches" },
  { code: "287", name: "Methodist churches; churches related to Methodism" },
  { code: "288", name: "No longer used — formerly Unitarian" },
  { code: "289", name: "Other denominations and sects" },
  { code: "290", name: "Other religions" },
  { code: "291", name: "No longer used — formerly Comparative religion" },
  { code: "292", name: "Classical religion (Greek and Roman religion)" },
  { code: "293", name: "Germanic religion" },
  { code: "294", name: "Religions of Indic origin" },
  { code: "295", name: "Zoroastrianism (Mazdaism, Parseeism)" },
  { code: "296", name: "Judaism" },
  { code: "297", name: "Islam, Bábism, and Baháʼí Faith" },
  { code: "298", name: "No longer used — formerly Mormonism" },
  { code: "299", name: "Religions not provided for elsewhere" },
  { code: "300", name: "Social sciences" },
  { code: "301", name: "Sociology and anthropology" },
  { code: "302", name: "Social interaction" },
  { code: "303", name: "Social processes" },
  { code: "304", name: "Factors affecting social behavior" },
  { code: "305", name: "Groups of people" },
  { code: "306", name: "Culture and institutions" },
  { code: "307", name: "Communities" },
  { code: "308", name: "No longer used — formerly Polygraphy" },
  { code: "309", name: "No longer used — formerly History of sociology" },
  { code: "310", name: "Collections of general statistics" },
  { code: "311", name: "No longer used — formerly Theory and methods" },
  { code: "312", name: "No longer used — formerly Population" },
  { code: "313", name: "No longer used — formerly Special topics" },
  { code: "314", name: "General statistics of Europe" },
  { code: "315", name: "General statistics of Asia" },
  { code: "316", name: "General statistics of Africa" },
  { code: "317", name: "General statistics of North America" },
  { code: "318", name: "General statistics of South America" },
  { code: "319", name: "General statistics of Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica" },
  { code: "320", name: "Political science (politics and government)" },
  { code: "321", name: "Systems of governments and states" },
  { code: "322", name: "Relation of state to organized groups and their members" },
  { code: "323", name: "Civil and political rights" },
  { code: "324", name: "Political process" },
  { code: "325", name: "International migration and colonization" },
  { code: "326", name: "Slavery and emancipation" },
  { code: "327", name: "International relations" },
  { code: "328", name: "The legislative process" },
  { code: "329", name: "No longer used— formerly Political parties" },
  { code: "330", name: "Economics" },
  { code: "331", name: "Labor economics" },
  { code: "332", name: "Financial economics" },
  { code: "333", name: "Economics of land and energy" },
  { code: "334", name: "Cooperatives" },
  { code: "335", name: "Socialism and related systems" },
  { code: "336", name: "Public finance" },
  { code: "337", name: "International economics" },
  { code: "338", name: "Production" },
  { code: "339", name: "Macroeconomics and related topics" },
  { code: "340", name: "Law" },
  { code: "341", name: "Law of nations" },
  { code: "342", name: "Constitutional and administrative law" },
  { code: "343", name: "Military, defense, public property, public finance, tax, commerce (trade), industrial law" },
  { code: "344", name: "Labor, social service, education, cultural law" },
  { code: "345", name: "Criminal law" },
  { code: "346", name: "Private law" },
  { code: "347", name: "Procedure and courts" },
  { code: "348", name: "Laws, regulations, cases" },
  { code: "349", name: "Law of specific jurisdictions, areas, socioeconomic regions, regional intergovernmental organizations" },
  { code: "350", name: "Public administration and military science" },
  { code: "351", name: "Public administration" },
  { code: "352", name: "General considerations of public administration" },
  { code: "353", name: "Specific fields of public administration" },
  { code: "354", name: "Public administration of economy and environment" },
  { code: "355", name: "Military science" },
  { code: "356", name: "Foot forces and warfare" },
  { code: "357", name: "Mounted forces and warfare" },
  { code: "358", name: "Air and other specialized forces and warfare; engineering and related services" },
  { code: "359", name: "Sea forces and warfare" },
  { code: "360", name: "Social problems and services; associations" },
  { code: "361", name: "Social problems and services" },
  { code: "362", name: "Social problems of and services to groups of people" },
  { code: "363", name: "Other social problems and services" },
  { code: "364", name: "Criminology", keywords: ["true crime"] },
  { code: "365", name: "Penal and related institutions" },
  { code: "366", name: "Secret associations and societies" },
  { code: "367", name: "General clubs" },
  { code: "368", name: "Insurance" },
  { code: "369", name: "Associations" },
  { code: "370", name: "Education" },
  { code: "371", name: "Schools and their activities, special education" },
  { code: "372", name: "Primary education (elementary education)" },
  { code: "373", name: "Secondary education" },
  { code: "374", name: "Adult education" },
  { code: "375", name: "Curriculum" },
  { code: "376", name: "No longer used — formerly Education of women" },
  { code: "377", name: "No longer used — formerly Ethical education" },
  { code: "378", name: "Higher education (tertiary education)" },
  { code: "379", name: "Public policy issues in education" },
  { code: "380", name: "Commerce, communications, transportation" },
  { code: "381", name: "Commerce (trade)" },
  { code: "382", name: "International commerce (foreign trade)" },
  { code: "383", name: "Postal communication" },
  { code: "384", name: "Communications" },
  { code: "385", name: "Railroad transportation" },
  { code: "386", name: "Inland waterway and ferry transportation" },
  { code: "387", name: "Water, air, space transportation" },
  { code: "388", name: "Transportation" },
  { code: "389", name: "Metrology and standardization" },
  { code: "390", name: "Customs, etiquette, folklore" },
  { code: "391", name: "Costume and personal appearance" },
  { code: "392", name: "Customs of life cycle and domestic life" },
  { code: "393", name: "Death customs" },
  { code: "394", name: "General customs" },
  { code: "395", name: "Etiquette (manners)" },
  { code: "396", name: "No longer used — formerly Women's position and treatment" },
  { code: "397", name: "No longer used — formerly Outcast studies" },
  { code: "398", name: "Folklore" },
  { code: "399", name: "Customs of war and diplomacy" },
  { code: "400", name: "Language" },
  { code: "401", name: "Philosophy and theory, international languages" },
  { code: "402", name: "Miscellany" },
  { code: "403", name: "Dictionaries, encyclopedias, concordances" },
  { code: "404", name: "Special topics of language" },
  { code: "405", name: "Serial publications" },
  { code: "406", name: "Organizations and management" },
  { code: "407", name: "Education, research, related topics" },
  { code: "408", name: "Groups of people" },
  { code: "409", name: "Geographic treatment and biography" },
  { code: "410", name: "Linguistics" },
  { code: "411", name: "Writing systems of standard forms of languages" },
  { code: "412", name: "Etymology of standard forms of languages" },
  { code: "413", name: "Dictionaries of standard forms of languages" },
  { code: "414", name: "Phonology and phonetics of standard forms of languages" },
  { code: "415", name: "Grammar of standard forms of languages" },
  { code: "416", name: "No longer used — formerly Prosody" },
  { code: "417", name: "Dialectology and historical linguistics" },
  { code: "418", name: "Standard usage (Prescriptive linguistics)" },
  { code: "419", name: "Sign languages" },
  { code: "420", name: "English and Old English (Anglo-Saxon)" },
  { code: "421", name: "Writing system, phonology, phonetics of standard English" },
  { code: "422", name: "Etymology of standard English" },
  { code: "423", name: "Dictionaries of standard English" },
  { code: "424", name: "No longer used — formerly English thesauruses" },
  { code: "425", name: "Grammar of standard English" },
  { code: "426", name: "No longer used — formerly English prosodies" },
  { code: "427", name: "Historical and geographical variations, modern nongeographic variations of English" },
  { code: "428", name: "Standard English usage (Prescriptive linguistics)" },
  { code: "429", name: "Old English (Anglo-Saxon)" },
  { code: "430", name: "German and related languages" },
  { code: "431", name: "Writing systems, phonology, phonetics of standard German" },
  { code: "432", name: "Etymology of standard German" },
  { code: "433", name: "Dictionaries of standard German" },
  { code: "434", name: "Not assigned or no longer used" },
  { code: "435", name: "Grammar of standard German" },
  { code: "436", name: "Not assigned or no longer used" },
  { code: "437", name: "Historical and geographic variations, modern nongeographic variations of German" },
  { code: "438", name: "Standard German usage (Prescriptive linguistics)" },
  { code: "439", name: "Other Germanic languages" },
  { code: "440", name: "French and related Romance languages" },
  { code: "441", name: "Writing systems, phonology, phonetics of standard French" },
  { code: "442", name: "Etymology of standard French" },
  { code: "443", name: "Dictionaries of standard French" },
  { code: "444", name: "Not assigned or no longer used" },
  { code: "445", name: "Grammar of standard French" },
  { code: "446", name: "Not assigned or no longer used" },
  { code: "447", name: "Historical and geographic variations, modern nongeographic variations of French" },
  { code: "448", name: "Standard French usage (Prescriptive linguistics)" },
  { code: "449", name: "Occitan, Catalan, Franco-Provençal" },
  { code: "450", name: "Italian, Dalmatian, Romanian, Rhaetian, Sardinian, Corsican" },
  { code: "451", name: "Writing systems, phonology, phonetics of standard Italian" },
  { code: "452", name: "Etymology of standard Italian" },
  { code: "453", name: "Dictionaries of standard Italian" },
  { code: "454", name: "Not assigned or no longer used" },
  { code: "455", name: "Grammar of standard Italian" },
  { code: "456", name: "Not assigned or no longer used" },
  { code: "457", name: "Historical and geographic variations, modern nongeographic variations of Italian" },
  { code: "458", name: "Standard Italian usage (Prescriptive linguistics)" },
  { code: "459", name: "Romanian, Rhaetian, Sardinian, Corsican" },
  { code: "460", name: "Spanish, Portuguese, Galician" },
  { code: "461", name: "Writing systems, phonology, phonetics of standard Spanish" },
  { code: "462", name: "Etymology of standard Spanish" },
  { code: "463", name: "Dictionaries of standard Spanish" },
  { code: "464", name: "Not assigned or no longer used" },
  { code: "465", name: "Grammar of standard Spanish" },
  { code: "466", name: "Not assigned or no longer used" },
  { code: "467", name: "Historical and geographic variations, modern nongeographic variations of Spanish" },
  { code: "468", name: "Standard Spanish usage (Prescriptive linguistics)" },
  { code: "469", name: "Portuguese" },
  { code: "470", name: "Latin and related Italic languages" },
  { code: "471", name: "Writing systems, phonology, phonetics of classical Latin" },
  { code: "472", name: "Etymology of classical Latin" },
  { code: "473", name: "Dictionaries of classical Latin" },
  { code: "474", name: "Not assigned or no longer used" },
  { code: "475", name: "Grammar of classical Latin" },
  { code: "476", name: "Not assigned or no longer used" },
  { code: "477", name: "Old, postclassical, vulgar Latin" },
  { code: "478", name: "Classical Latin usage (Prescriptive linguistics)" },
  { code: "479", name: "Other Italic languages" },
  { code: "480", name: "Classical Greek and related Hellenic languages" },
  { code: "481", name: "Writing systems, phonology, phonetics of classical Greek" },
  { code: "482", name: "Etymology of classical Greek" },
  { code: "483", name: "Dictionaries of classical Greek" },
  { code: "484", name: "Not assigned or no longer used" },
  { code: "485", name: "Grammar of classical Greek" },
  { code: "486", name: "Not assigned or no longer used" },
  { code: "487", name: "Preclassical and postclassical Greek" },
  { code: "488", name: "Classical Greek usage (Prescriptive linguistics)" },
  { code: "489", name: "Other Hellenic languages" },
  { code: "490", name: "Other languages" },
  { code: "491", name: "East Indo-European and Celtic languages" },
  { code: "492", name: "Afro-Asiatic languages" },
  { code: "493", name: "Non-Semitic Afro-Asiatic languages" },
  { code: "494", name: "Altaic, Uralic, Hyperborean, Dravidian languages, miscellaneous languages of South Asia" },
  { code: "495", name: "Languages of East Asia and Southeast Asia" },
  { code: "496", name: "African languages" },
  { code: "497", name: "North American native languages" },
  { code: "498", name: "South American native languages" },
  { code: "499", name: "Non-Austronesian languages of Oceania, Austronesian languages, miscellaneous languages" },
  { code: "500", name: "Natural sciences and mathematics" },
  { code: "501", name: "Philosophy and theory" },
  { code: "502", name: "Miscellany" },
  { code: "503", name: "Dictionaries, encyclopedias, concordances" },
  { code: "504", name: "Not assigned or no longer used" },
  { code: "505", name: "Serial publications" },
  { code: "506", name: "Organizations and management" },
  { code: "507", name: "Education, research, related topics" },
  { code: "508", name: "Natural history" },
  { code: "509", name: "History, geographic treatment, biography" },
  { code: "510", name: "Mathematics" },
  { code: "511", name: "General principles of mathematics" },
  { code: "512", name: "Algebra" },
  { code: "513", name: "Arithmetic" },
  { code: "514", name: "Topology" },
  { code: "515", name: "Analysis" },
  { code: "516", name: "Geometry" },
  { code: "517", name: "Not assigned or no longer used" },
  { code: "518", name: "Numerical analysis" },
  { code: "519", name: "Probabilities and applied mathematics" },
  { code: "520", name: "Astronomy and allied sciences" },
  { code: "521", name: "Celestial mechanics" },
  { code: "522", name: "Techniques, procedures, apparatus, equipment, materials" },
  { code: "523", name: "Specific celestial bodies and phenomena", keywords: ["planets", "stars", "galaxies", "black holes", "the solar system"] },
  { code: "524", name: "Not assigned or no longer used" },
  { code: "525", name: "Earth (Astronomical geography)" },
  { code: "526", name: "Mathematical geography" },
  { code: "527", name: "Celestial navigation" },
  { code: "528", name: "Ephemerides" },
  { code: "529", name: "Chronology" },
  { code: "530", name: "Physics" },
  { code: "531", name: "Classical mechanics" },
  { code: "532", name: "Fluid mechanics" },
  { code: "533", name: "Pneumatics (Gas mechanics)" },
  { code: "534", name: "Sound and related vibrations" },
  { code: "535", name: "Light and related radiation" },
  { code: "536", name: "Heat" },
  { code: "537", name: "Electricity and electronics" },
  { code: "538", name: "Magnetism" },
  { code: "539", name: "Modern physics" },
  { code: "540", name: "Chemistry and allied sciences" },
  { code: "541", name: "Physical chemistry" },
  { code: "542", name: "Techniques, procedures, apparatus, equipment, materials" },
  { code: "543", name: "Analytical chemistry" },
  { code: "544", name: "No longer used — formerly Qualitative analysis" },
  { code: "545", name: "No longer used — formerly Quantitative analysis" },
  { code: "546", name: "Inorganic chemistry" },
  { code: "547", name: "Organic chemistry" },
  { code: "548", name: "Crystallography" },
  { code: "549", name: "Mineralogy" },
  { code: "550", name: "Earth sciences" },
  { code: "551", name: "Geology, hydrology, meteorology" },
  { code: "552", name: "Petrology" },
  { code: "553", name: "Economic geology" },
  { code: "554", name: "Earth sciences of Europe" },
  { code: "555", name: "Earth sciences of Asia" },
  { code: "556", name: "Earth sciences of Africa" },
  { code: "557", name: "Earth sciences of North America" },
  { code: "558", name: "Earth sciences of South America" },
  { code: "559", name: "Earth sciences of Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica, extraterrestrial worlds" },
  { code: "560", name: "Paleontology" },
  { code: "561", name: "Paleobotany, fossil microorganisms" },
  { code: "562", name: "Fossil invertebrates" },
  { code: "563", name: "Miscellaneous fossil marine and seashore invertebrates" },
  { code: "564", name: "Fossil Mollusca and Molluscoidea" },
  { code: "565", name: "Fossil Arthropoda" },
  { code: "566", name: "Fossil Chordata" },
  { code: "567", name: "Fossil cold-blooded vertebrates" },
  { code: "568", name: "Fossil Aves (birds)" },
  { code: "569", name: "Fossil Mammalia" },
  { code: "570", name: "Biology" },
  { code: "571", name: "Physiology and related subjects" },
  { code: "572", name: "Biochemistry" },
  { code: "573", name: "Specific physiological systems in animals, regional histology and physiology in animals" },
  { code: "574", name: "Not assigned or no longer used" },
  { code: "575", name: "Specific parts of and physiological systems in plants" },
  { code: "576", name: "Genetics and evolution" },
  { code: "577", name: "Ecology" },
  { code: "578", name: "Natural history of organisms and related subjects" },
  { code: "579", name: "Natural history of microorganisms, fungi, algae" },
  { code: "580", name: "Plants" },
  { code: "581", name: "Specific topics in natural history of plants" },
  { code: "582", name: "Plants noted for specific vegetative characteristics and flowers" },
  { code: "583", name: "Magnoliopsida (Dicotyledones)" },
  { code: "584", name: "Liliopsida (Monocotyledones)" },
  { code: "585", name: "Pinophyta (Gymnosperms)" },
  { code: "586", name: "Cryptogamia (seedless plants)" },
  { code: "587", name: "Pteridophyta" },
  { code: "588", name: "Bryophyta" },
  { code: "589", name: "No longer used—formerly Forestry" },
  { code: "590", name: "Animals" },
  { code: "591", name: "Specific topics in natural history of animals" },
  { code: "592", name: "Invertebrates" },
  { code: "593", name: "Miscellaneous marine and seashore invertebrates" },
  { code: "594", name: "Mollusca and Molluscoidea" },
  { code: "595", name: "Arthropoda" },
  { code: "596", name: "Chordata" },
  { code: "597", name: "Cold-blooded vertebrates" },
  { code: "598", name: "Aves (birds)" },
  { code: "599", name: "Mammalia (mammals)" },
  { code: "600", name: "Technology (applied sciences)" },
  { code: "601", name: "Philosophy and theory" },
  { code: "602", name: "Miscellany" },
  { code: "603", name: "Dictionaries, encyclopedias, concordances" },
  { code: "604", name: "Technical drawing, hazardous materials technology; groups of people" },
  { code: "605", name: "Serial publications" },
  { code: "606", name: "Organizations" },
  { code: "607", name: "Education, research, related topics" },
  { code: "608", name: "Patents" },
  { code: "609", name: "History, geographic treatment, biography" },
  { code: "610", name: "Medicine and health" },
  { code: "611", name: "Human anatomy, cytology, histology" },
  { code: "612", name: "Human physiology" },
  { code: "613", name: "Personal health and safety", keywords: ["fitness", "nutrition", "exercise", "wellness"] },
  { code: "614", name: "Forensic medicine; incidence of injuries, wounds, disease; public preventive medicine" },
  { code: "615", name: "Pharmacology and therapeutics", keywords: ["medicine", "drugs", "pharmacy"] },
  { code: "616", name: "Diseases", keywords: ["cancer", "diabetes", "illness"] },
  { code: "617", name: "Surgery, regional medicine, dentistry, ophthalmology, otology, audiology" },
  { code: "618", name: "Gynecology, obstetrics, pediatrics, geriatrics" },
  { code: "619", name: "No longer used—formerly Experimental medicine" },
  { code: "620", name: "Engineering and applied operations" },
  { code: "621", name: "Applied physics" },
  { code: "622", name: "Mining and related operations" },
  { code: "623", name: "Military and nautical engineering" },
  { code: "624", name: "Civil engineering" },
  { code: "625", name: "Engineering of railroads, roads" },
  { code: "626", name: "Not assigned or no longer used" },
  { code: "627", name: "Hydraulic engineering" },
  { code: "628", name: "Sanitary engineering" },
  { code: "629", name: "Other branches of engineering", keywords: ["cars", "automobiles", "airplanes", "spacecraft"] },
  { code: "630", name: "Agriculture and related technologies" },
  { code: "631", name: "Specific techniques; apparatus, equipment, materials" },
  { code: "632", name: "Plant injuries, diseases, pests" },
  { code: "633", name: "Field and plantation crops" },
  { code: "634", name: "Orchards, fruits, forestry" },
  { code: "635", name: "Garden crops (horticulture)", keywords: ["gardening"] },
  { code: "636", name: "Animal husbandry", keywords: ["pets", "dogs", "cats", "livestock"] },
  { code: "637", name: "Processing dairy and related products" },
  { code: "638", name: "Insect culture" },
  { code: "639", name: "Hunting, fishing, conservation, related technologies" },
  { code: "640", name: "Home and family management" },
  { code: "641", name: "Food and drink", keywords: ["cooking", "recipes"] },
  { code: "642", name: "Meals and table service" },
  { code: "643", name: "Housing and household equipment" },
  { code: "644", name: "Household utilities" },
  { code: "645", name: "Household furnishings" },
  { code: "646", name: "Sewing, clothing, management of personal and family life" },
  { code: "647", name: "Management of public households (institutional housekeeping)" },
  { code: "648", name: "Housekeeping" },
  { code: "649", name: "Child rearing; home care of people with disabilities and illnesses", keywords: ["parenting", "child care"] },
  { code: "650", name: "Management and auxiliary services" },
  { code: "651", name: "Office services" },
  { code: "652", name: "Processes of written communication" },
  { code: "653", name: "Shorthand" },
  { code: "654", name: "Not assigned or no longer used" },
  { code: "655", name: "Not assigned or no longer used" },
  { code: "656", name: "Not assigned or no longer used" },
  { code: "657", name: "Accounting" },
  { code: "658", name: "General management" },
  { code: "659", name: "Advertising and public relations" },
  { code: "660", name: "Chemical engineering and related technologies" },
  { code: "661", name: "Technology of industrial chemicals" },
  { code: "662", name: "Technology of explosives, fuels, related products" },
  { code: "663", name: "Beverage technology" },
  { code: "664", name: "Food technology" },
  { code: "665", name: "Technology of industrial oils, fats, waxes, gases" },
  { code: "666", name: "Ceramic and allied technologies" },
  { code: "667", name: "Cleaning, color, coating, related technologies" },
  { code: "668", name: "Technology of other organic products" },
  { code: "669", name: "Metallurgy" },
  { code: "670", name: "Manufacturing" },
  { code: "671", name: "Metalworking processes and primary metal products" },
  { code: "672", name: "Iron, steel, other iron alloys" },
  { code: "673", name: "Nonferrous metals" },
  { code: "674", name: "Lumber processing, wood products, cork" },
  { code: "675", name: "Leather processing and fur processing" },
  { code: "676", name: "Pulp and paper technology" },
  { code: "677", name: "Textiles" },
  { code: "678", name: "Elastomers and elastomer products" },
  { code: "679", name: "Other products of specific kinds of materials" },
  { code: "680", name: "Manufacture of products for specific uses" },
  { code: "681", name: "Precision instruments and other devices" },
  { code: "682", name: "Small forge work (blacksmithing)" },
  { code: "683", name: "Hardware and household appliances" },
  { code: "684", name: "Furnishings and home workshops" },
  { code: "685", name: "Leather and fur goods, and related products" },
  { code: "686", name: "Printing and related activities" },
  { code: "687", name: "Clothing and accessories" },
  { code: "688", name: "Other final products, and packaging technology" },
  { code: "689", name: "Not assigned or no longer used" },
  { code: "690", name: "Construction of buildings" },
  { code: "691", name: "Building materials" },
  { code: "692", name: "Auxiliary construction practices" },
  { code: "693", name: "Construction in specific types of materials and for specific purposes" },
  { code: "694", name: "Wood construction" },
  { code: "695", name: "Roof covering" },
  { code: "696", name: "Utilities" },
  { code: "697", name: "Heating, ventilating, air-conditioning engineering" },
  { code: "698", name: "Detail finishing" },
  { code: "699", name: "Not assigned or no longer used" },
  { code: "700", name: "The arts" },
  { code: "701", name: "Philosophy and theory of fine arts and decorative arts" },
  { code: "702", name: "Miscellany of fine and decorative arts" },
  { code: "703", name: "Dictionaries, encyclopedias, concordances of fine and decorative arts" },
  { code: "704", name: "Special topics in fine and decorative arts" },
  { code: "705", name: "Serial publications of fine and decorative arts" },
  { code: "706", name: "Organizations and management of fine and decorative arts" },
  { code: "707", name: "Education, research, related topics of fine and decorative arts" },
  { code: "708", name: "Galleries, museums, private collections of fine and decorative arts" },
  { code: "709", name: "History, geographic treatment, biography" },
  { code: "710", name: "Area planning and landscape architecture" },
  { code: "711", name: "Area planning (civic art)" },
  { code: "712", name: "Landscape architecture (Landscape design)" },
  { code: "713", name: "Landscape architecture of trafficways" },
  { code: "714", name: "Water features in landscape architecture" },
  { code: "715", name: "Woody plants in landscape architecture" },
  { code: "716", name: "Herbaceous plants in landscape architecture" },
  { code: "717", name: "Structures in landscape architecture" },
  { code: "718", name: "Landscape design of cemeteries" },
  { code: "719", name: "Natural landscapes" },
  { code: "720", name: "Architecture" },
  { code: "721", name: "Architectural materials and structural elements" },
  { code: "722", name: "Architecture from earliest times to c. 300" },
  { code: "723", name: "Architecture from c. 300 to 1399" },
  { code: "724", name: "Architecture from 1400" },
  { code: "725", name: "Public structures" },
  { code: "726", name: "Buildings for religious and related purposes" },
  { code: "727", name: "Buildings for educational and research purposes" },
  { code: "728", name: "Residential and related buildings" },
  { code: "729", name: "Design and decoration of structures and accessories" },
  { code: "730", name: "Sculpture and related arts" },
  { code: "731", name: "Processes, forms, subjects of sculpture" },
  { code: "732", name: "Sculpture from earliest times to c. 500, sculpture of non-literate peoples" },
  { code: "733", name: "Greek, Etruscan, Roman sculpture" },
  { code: "734", name: "Sculpture from ca 500 to 1399" },
  { code: "735", name: "Sculpture from 1400" },
  { code: "736", name: "Carving and carvings" },
  { code: "737", name: "Numismatics and sigillography" },
  { code: "738", name: "Ceramic arts" },
  { code: "739", name: "Art metalwork" },
  { code: "740", name: "Graphic arts" },
  { code: "741", name: "Drawing and drawings" },
  { code: "742", name: "Perspective in drawing" },
  { code: "743", name: "Drawing and drawings by subject" },
  { code: "744", name: "Communication design and visual design" },
  { code: "745", name: "Decorative arts", keywords: ["crafts", "diy", "handicrafts"] },
  { code: "746", name: "Textile arts" },
  { code: "747", name: "Interior decoration" },
  { code: "748", name: "Glass" },
  { code: "749", name: "Furniture and accessories" },
  { code: "750", name: "Painting and paintings" },
  { code: "751", name: "Techniques, procedures, apparatus, equipment, materials, forms" },
  { code: "752", name: "Color" },
  { code: "753", name: "Symbolism, allegory, mythology, legend" },
  { code: "754", name: "Genre paintings" },
  { code: "755", name: "Religion" },
  { code: "756", name: "Not assigned or no longer used" },
  { code: "757", name: "Human figures" },
  { code: "758", name: "Nature, architectural subjects and cityscapes, other specific subjects" },
  { code: "759", name: "History, geographic treatment, biography" },
  { code: "760", name: "Printmaking and prints" },
  { code: "761", name: "Relief processes (block printing)" },
  { code: "762", name: "Not assigned or no longer used" },
  { code: "763", name: "Lithographic processes (planographic processes)" },
  { code: "764", name: "Chromolithography and serigraphy" },
  { code: "765", name: "Metal engraving" },
  { code: "766", name: "Mezzotinting, aquatinting, and related processes" },
  { code: "767", name: "Etching and drypoint" },
  { code: "768", name: "Not assigned or no longer used" },
  { code: "769", name: "Prints" },
  { code: "770", name: "Photography, computer art, cinematography, videography" },
  { code: "771", name: "Techniques, procedures, apparatus, equipment, materials" },
  { code: "772", name: "Metallic salt processes" },
  { code: "773", name: "Pigment processes of printing" },
  { code: "774", name: "No longer used—formerly Holography" },
  { code: "775", name: "No longer used—formerly Digital photography" },
  { code: "776", name: "Computer art (digital art)" },
  { code: "777", name: "Cinematography and videography" },
  { code: "778", name: "Specific fields and special kinds of photography" },
  { code: "779", name: "Photographic images" },
  { code: "780", name: "Music" },
  { code: "781", name: "General principles and musical forms" },
  { code: "782", name: "Vocal music" },
  { code: "783", name: "Music for single voices" },
  { code: "784", name: "Instruments and Instrumental ensembles and their music" },
  { code: "785", name: "Ensembles with only one instrument per part" },
  { code: "786", name: "Keyboard, mechanical, electrophonic, percussion instruments" },
  { code: "787", name: "Stringed instruments (chordophones)" },
  { code: "788", name: "Wind instruments (aerophones)" },
  { code: "789", name: "Not assigned or no longer used" },
  { code: "790", name: "Recreational arts and performing arts" },
  { code: "791", name: "Public performances" },
  { code: "792", name: "Stage presentations" },
  { code: "793", name: "Indoor games and amusements" },
  { code: "794", name: "Indoor games of skill", keywords: ["chess", "video games"] },
  { code: "795", name: "Games of chance" },
  { code: "796", name: "Athletic and outdoor sports and games", keywords: ["sports", "football", "basketball", "soccer"] },
  { code: "797", name: "Aquatic sports and air sports" },
  { code: "798", name: "Equestrian sports and animal racing", keywords: ["horse racing", "equestrian"] },
  { code: "799", name: "Fishing, hunting, shooting" },
  { code: "800", name: "Literature (Belles-lettres) and rhetoric" },
  { code: "801", name: "Philosophy and theory" },
  { code: "802", name: "Miscellany" },
  { code: "803", name: "Dictionaries, encyclopedias, concordances" },
  { code: "804", name: "Not assigned or no longer used" },
  { code: "805", name: "Serial publications" },
  { code: "806", name: "Organizations and management" },
  { code: "807", name: "Education, research, related topics" },
  { code: "808", name: "Rhetoric and collections of literary texts from more than two literatures" },
  { code: "809", name: "History, description, critical appraisal of more than two literatures" },
  { code: "810", name: "American literature in English" },
  { code: "811", name: "American poetry in English" },
  { code: "812", name: "American drama in English" },
  { code: "813", name: "American fiction in English" },
  { code: "814", name: "American essays in English" },
  { code: "815", name: "American speeches in English" },
  { code: "816", name: "American letters in English" },
  { code: "817", name: "American humor and satire in English" },
  { code: "818", name: "American miscellaneous writings in English" },
  { code: "819", name: "No longer used—formerly Puzzle activities" },
  { code: "820", name: "English and Old English (Anglo-Saxon) literatures" },
  { code: "821", name: "English poetry" },
  { code: "822", name: "English drama" },
  { code: "823", name: "English fiction" },
  { code: "824", name: "English essays" },
  { code: "825", name: "English speeches" },
  { code: "826", name: "English letters" },
  { code: "827", name: "English humor and satire" },
  { code: "828", name: "English miscellaneous writings" },
  { code: "829", name: "Old English (Anglo-Saxon) literature" },
  { code: "830", name: "German literature and literatures of related languages" },
  { code: "831", name: "German poetry" },
  { code: "832", name: "German drama" },
  { code: "833", name: "German fiction" },
  { code: "834", name: "German essays" },
  { code: "835", name: "German speeches" },
  { code: "836", name: "German letters" },
  { code: "837", name: "German humor and satire" },
  { code: "838", name: "German miscellaneous writings" },
  { code: "839", name: "Other Germanic literatures" },
  { code: "840", name: "French literature and literatures of related Romance languages" },
  { code: "841", name: "French poetry" },
  { code: "842", name: "French drama" },
  { code: "843", name: "French fiction" },
  { code: "844", name: "French essays" },
  { code: "845", name: "French speeches" },
  { code: "846", name: "French letters" },
  { code: "847", name: "French humor and satire" },
  { code: "848", name: "French miscellaneous writings" },
  { code: "849", name: "Occitan, Catalan, Franco-Provençal literatures" },
  { code: "850", name: "Literatures of Italian, Dalmatian, Romanian, Rhaetian, Sardinian, Corsican languages" },
  { code: "851", name: "Italian poetry" },
  { code: "852", name: "Italian drama" },
  { code: "853", name: "Italian fiction" },
  { code: "854", name: "Italian essays" },
  { code: "855", name: "Italian speeches" },
  { code: "856", name: "Italian letters" },
  { code: "857", name: "Italian humor and satire" },
  { code: "858", name: "Italian miscellaneous writings" },
  { code: "859", name: "Literatures of Romanian, Rhaetian, Sardinian, Corsican languages" },
  { code: "860", name: "Literatures of Spanish, Portuguese, Galician languages" },
  { code: "861", name: "Spanish poetry" },
  { code: "862", name: "Spanish drama" },
  { code: "863", name: "Spanish fiction" },
  { code: "864", name: "Spanish essays" },
  { code: "865", name: "Spanish speeches" },
  { code: "866", name: "Spanish letters" },
  { code: "867", name: "Spanish humor and satire" },
  { code: "868", name: "Spanish miscellaneous writings" },
  { code: "869", name: "Literatures of Portuguese and Galician languages" },
  { code: "870", name: "Latin literature and literatures of related Italic languages" },
  { code: "871", name: "Latin poetry" },
  { code: "872", name: "Latin dramatic poetry and drama" },
  { code: "873", name: "Latin epic poetry and fiction" },
  { code: "874", name: "Latin lyric poetry" },
  { code: "875", name: "Latin speeches" },
  { code: "876", name: "Latin letters" },
  { code: "877", name: "Latin humor and satire" },
  { code: "878", name: "Latin miscellaneous writings" },
  { code: "879", name: "Literatures of other Italic languages" },
  { code: "880", name: "Classical Greek literature and literatures of related Hellenic languages" },
  { code: "881", name: "Classical Greek poetry" },
  { code: "882", name: "Classical Greek drama" },
  { code: "883", name: "Classical Greek epic poetry and fiction" },
  { code: "884", name: "Classical Greek lyric poetry" },
  { code: "885", name: "Classical Greek speeches" },
  { code: "886", name: "Classical Greek letters" },
  { code: "887", name: "Classical Greek humor and satire" },
  { code: "888", name: "Classical Greek miscellaneous writings" },
  { code: "889", name: "Modern Greek literature" },
  { code: "890", name: "Literatures of other specific languages and language families" },
  { code: "891", name: "East Indo-European and Celtic literatures" },
  { code: "892", name: "Afro-Asiatic literatures" },
  { code: "893", name: "Non-Semitic Afro-Asiatic literatures" },
  { code: "894", name: "Literatures of Altaic, Uralic, Hyperborean, Dravidian languages; literatures of miscellaneous languages of South Asia" },
  { code: "895", name: "Literatures of East and Southeast Asia" },
  { code: "896", name: "African literatures" },
  { code: "897", name: "Literatures of North American native languages" },
  { code: "898", name: "Literatures of South American native languages" },
  { code: "899", name: "Literatures of non-Austronesian languages of Oceania, of Austronesian languages, of miscellaneous languages" },
  { code: "900", name: "History, geography, and auxiliary disciplines" },
  { code: "901", name: "Philosophy and theory of history" },
  { code: "902", name: "Miscellany of history" },
  { code: "903", name: "Dictionaries, encyclopedias, concordances of history" },
  { code: "904", name: "Collected accounts of events" },
  { code: "905", name: "Serial publications of history" },
  { code: "906", name: "Organizations and management of history" },
  { code: "907", name: "Education, research, related topics of history" },
  { code: "908", name: "History with respect to groups of people" },
  { code: "909", name: "World history" },
  { code: "910", name: "Geography and travel" },
  { code: "911", name: "Historical geography" },
  { code: "912", name: "Graphic representations of surface of Earth and of extraterrestrial worlds" },
  { code: "913", name: "Geography of and travel in the ancient world" },
  { code: "914", name: "Geography of and travel in Europe" },
  { code: "915", name: "Geography of and travel in Asia" },
  { code: "916", name: "Geography of and travel in Africa" },
  { code: "917", name: "Geography of and travel in North America" },
  { code: "918", name: "Geography of and travel in South America" },
  { code: "919", name: "Geography of and travel in Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica, and on extraterrestrial worlds" },
  { code: "920", name: "Biography, genealogy, insignia" },
  { code: "921", name: "This range is reserved as an optional location for biographies, which are shelved alphabetically by subject's last name." },
  { code: "922", name: "This range is reserved as an optional location for biographies, which are shelved alphabetically by subject's last name." },
  { code: "923", name: "This range is reserved as an optional location for biographies, which are shelved alphabetically by subject's last name." },
  { code: "924", name: "This range is reserved as an optional location for biographies, which are shelved alphabetically by subject's last name." },
  { code: "925", name: "This range is reserved as an optional location for biographies, which are shelved alphabetically by subject's last name." },
  { code: "926", name: "This range is reserved as an optional location for biographies, which are shelved alphabetically by subject's last name." },
  { code: "927", name: "This range is reserved as an optional location for biographies, which are shelved alphabetically by subject's last name." },
  { code: "928", name: "This range is reserved as an optional location for biographies, which are shelved alphabetically by subject's last name." },
  { code: "929", name: "Genealogy, names, insignia" },
  { code: "930", name: "History of ancient world to c. 499" },
  { code: "931", name: "China to 420" },
  { code: "932", name: "Egypt to 640" },
  { code: "933", name: "Palestine to 70" },
  { code: "934", name: "South Asia to 647" },
  { code: "935", name: "Mesopotamia and Iranian Plateau to 637" },
  { code: "936", name: "Europe north and west of Italian Peninsula to c. 499" },
  { code: "937", name: "Italy and adjacent territories to 476" },
  { code: "938", name: "Greece to 323" },
  { code: "939", name: "Other parts of ancient world" },
  { code: "940", name: "History of Europe" },
  { code: "941", name: "Ireland and the British Isles" },
  { code: "942", name: "England and Wales" },
  { code: "943", name: "Germany and neighboring central European countries" },
  { code: "944", name: "France and Monaco" },
  { code: "945", name: "Italy, San Marino, Vatican City, Malta" },
  { code: "946", name: "Spain, Andorra, Gibraltar, Portugal" },
  { code: "947", name: "Russia and neighboring east European countries" },
  { code: "948", name: "Scandinavia" },
  { code: "949", name: "Other parts of Europe" },
  { code: "950", name: "History of Asia" },
  { code: "951", name: "China and adjacent areas" },
  { code: "952", name: "Japan" },
  { code: "953", name: "Arabian Peninsula and adjacent areas" },
  { code: "954", name: "India and neighboring south Asian countries" },
  { code: "955", name: "Iran" },
  { code: "956", name: "Middle East (near East)" },
  { code: "957", name: "Siberia (Asiatic Russia)" },
  { code: "958", name: "Central Asia" },
  { code: "959", name: "Southeast Asia" },
  { code: "960", name: "History of Africa" },
  { code: "961", name: "Tunisia and Libya" },
  { code: "962", name: "Egypt, Sudan, South Sudan" },
  { code: "963", name: "Ethiopia and Eritrea" },
  { code: "964", name: "Morocco, Ceuta, Melilla, Western Sahara, Canary Islands" },
  { code: "965", name: "Algeria" },
  { code: "966", name: "West Africa and offshore islands" },
  { code: "967", name: "Central Africa and offshore islands" },
  { code: "968", name: "South Africa and southern Africa" },
  { code: "969", name: "South Indian Ocean islands" },
  { code: "970", name: "History of North America" },
  { code: "971", name: "Canada" },
  { code: "972", name: "Mexico, Central America, West Indies, Bermuda" },
  { code: "973", name: "United States" },
  { code: "974", name: "Northeastern United States (New England and Middle Atlantic states)" },
  { code: "975", name: "Southeastern United States (South Atlantic states)" },
  { code: "976", name: "South central United States" },
  { code: "977", name: "North central United States" },
  { code: "978", name: "Western United States" },
  { code: "979", name: "Great Basin and Pacific Slope region of United States" },
  { code: "980", name: "History of South America" },
  { code: "981", name: "Brazil" },
  { code: "982", name: "Argentina" },
  { code: "983", name: "Chile" },
  { code: "984", name: "Bolivia" },
  { code: "985", name: "Peru" },
  { code: "986", name: "Colombia and Ecuador" },
  { code: "987", name: "Venezuela" },
  { code: "988", name: "Guiana" },
  { code: "989", name: "Paraguay and Uruguay" },
  { code: "990", name: "History of Australasia, Pacific Ocean islands, Atlantic Ocean islands, Arctic islands, Antarctica, extraterrestrial worlds" },
  { code: "991", name: "Not assigned or no longer used" },
  { code: "992", name: "Not assigned or no longer used" },
  { code: "993", name: "New Zealand" },
  { code: "994", name: "Australia" },
  { code: "995", name: "New Guinea and neighboring countries of Melanesia" },
  { code: "996", name: "Polynesia and other Pacific Ocean islands" },
  { code: "997", name: "Atlantic Ocean islands" },
  { code: "998", name: "Arctic islands and Antarctica" },
  { code: "999", name: "Extraterrestrial worlds" },
];
